/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use super::{configuration, Error};
use crate::apis::ContentType;
use crate::{apis::ResponseContent, models};
use async_trait::async_trait;
use reqwest;
use serde::{de::Error as _, Deserialize, Serialize};
use std::sync::Arc;

#[async_trait]
pub trait AccountWebAuthnApi: Send + Sync {
    /// DELETE /api/auth/v1/account/authenticators/webauthn
    ///
    ///
    async fn allauth_account_authenticators_webauthn_delete(
        &self,
        params: AllauthAccountAuthenticatorsWebauthnDeleteParams,
    ) -> Result<
        models::AllauthAuthEmailVerifyResendPost200Response,
        Error<AllauthAccountAuthenticatorsWebauthnDeleteError>,
    >;

    /// GET /api/auth/v1/account/authenticators/webauthn
    ///
    /// Returns the WebAuthn credential creation options, that can be processed using `parseCreationOptionsFromJSON()` on the frontend.
    async fn allauth_account_authenticators_webauthn_get(
        &self,
        params: AllauthAccountAuthenticatorsWebauthnGetParams,
    ) -> Result<
        models::AllauthAccountAuthenticatorsWebauthnGet200Response,
        Error<AllauthAccountAuthenticatorsWebauthnGetError>,
    >;

    /// POST /api/auth/v1/account/authenticators/webauthn
    ///
    ///
    async fn allauth_account_authenticators_webauthn_post(
        &self,
        params: AllauthAccountAuthenticatorsWebauthnPostParams,
    ) -> Result<
        models::AllauthAccountAuthenticatorsWebauthnPost200Response,
        Error<AllauthAccountAuthenticatorsWebauthnPostError>,
    >;

    /// PUT /api/auth/v1/account/authenticators/webauthn
    ///
    /// You can alter the name of a WebAuthn credential by PUT'ting the ID and name of the authenticator representing that credential. You can obtain the credentials via the \"List authenticators\" endpoint.
    async fn allauth_account_authenticators_webauthn_put(
        &self,
        params: AllauthAccountAuthenticatorsWebauthnPutParams,
    ) -> Result<
        models::AllauthAccountAuthenticatorsWebauthnPut200Response,
        Error<AllauthAccountAuthenticatorsWebauthnPutError>,
    >;
}

pub struct AccountWebAuthnApiClient {
    configuration: Arc<configuration::Configuration>,
}

impl AccountWebAuthnApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}

/// struct for passing parameters to the method [`AccountWebAuthnApi::allauth_account_authenticators_webauthn_delete`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder), builder(finish_fn = build_struct))]
pub struct AllauthAccountAuthenticatorsWebauthnDeleteParams {
    pub allauth_account_authenticators_webauthn_delete_request:
        Option<models::AllauthAccountAuthenticatorsWebauthnDeleteRequest>,
}

/// struct for passing parameters to the method [`AccountWebAuthnApi::allauth_account_authenticators_webauthn_get`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder), builder(finish_fn = build_struct))]
pub struct AllauthAccountAuthenticatorsWebauthnGetParams {
    /// When present (regardless of its value), enables passwordless sign-in via a WebAuthn credential (Passkey), but may enforce additional multi-factor authentication (MFA) requirements. Omit the parameter to disable.
    pub passwordless: Option<bool>,
}

/// struct for passing parameters to the method [`AccountWebAuthnApi::allauth_account_authenticators_webauthn_post`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder), builder(finish_fn = build_struct))]
pub struct AllauthAccountAuthenticatorsWebauthnPostParams {
    pub allauth_auth_webauthn_signup_put_request:
        Option<models::AllauthAuthWebauthnSignupPutRequest>,
}

/// struct for passing parameters to the method [`AccountWebAuthnApi::allauth_account_authenticators_webauthn_put`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder), builder(finish_fn = build_struct))]
pub struct AllauthAccountAuthenticatorsWebauthnPutParams {
    pub allauth_account_authenticators_webauthn_put_request:
        Option<models::AllauthAccountAuthenticatorsWebauthnPutRequest>,
}

#[async_trait]
impl AccountWebAuthnApi for AccountWebAuthnApiClient {
    async fn allauth_account_authenticators_webauthn_delete(
        &self,
        params: AllauthAccountAuthenticatorsWebauthnDeleteParams,
    ) -> Result<
        models::AllauthAuthEmailVerifyResendPost200Response,
        Error<AllauthAccountAuthenticatorsWebauthnDeleteError>,
    > {
        let AllauthAccountAuthenticatorsWebauthnDeleteParams {
            allauth_account_authenticators_webauthn_delete_request,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/auth/v1/account/authenticators/webauthn",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::DELETE, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder =
            local_var_req_builder.json(&allauth_account_authenticators_webauthn_delete_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AllauthAuthEmailVerifyResendPost200Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AllauthAuthEmailVerifyResendPost200Response`")))),
            }
        } else {
            let local_var_entity: Option<AllauthAccountAuthenticatorsWebauthnDeleteError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Returns the WebAuthn credential creation options, that can be processed using `parseCreationOptionsFromJSON()` on the frontend.
    async fn allauth_account_authenticators_webauthn_get(
        &self,
        params: AllauthAccountAuthenticatorsWebauthnGetParams,
    ) -> Result<
        models::AllauthAccountAuthenticatorsWebauthnGet200Response,
        Error<AllauthAccountAuthenticatorsWebauthnGetError>,
    > {
        let AllauthAccountAuthenticatorsWebauthnGetParams { passwordless } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/auth/v1/account/authenticators/webauthn",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref param_value) = passwordless {
            local_var_req_builder =
                local_var_req_builder.query(&[("passwordless", &param_value.to_string())]);
        }
        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AllauthAccountAuthenticatorsWebauthnGet200Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AllauthAccountAuthenticatorsWebauthnGet200Response`")))),
            }
        } else {
            let local_var_entity: Option<AllauthAccountAuthenticatorsWebauthnGetError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    async fn allauth_account_authenticators_webauthn_post(
        &self,
        params: AllauthAccountAuthenticatorsWebauthnPostParams,
    ) -> Result<
        models::AllauthAccountAuthenticatorsWebauthnPost200Response,
        Error<AllauthAccountAuthenticatorsWebauthnPostError>,
    > {
        let AllauthAccountAuthenticatorsWebauthnPostParams {
            allauth_auth_webauthn_signup_put_request,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/auth/v1/account/authenticators/webauthn",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder =
            local_var_req_builder.json(&allauth_auth_webauthn_signup_put_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AllauthAccountAuthenticatorsWebauthnPost200Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AllauthAccountAuthenticatorsWebauthnPost200Response`")))),
            }
        } else {
            let local_var_entity: Option<AllauthAccountAuthenticatorsWebauthnPostError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// You can alter the name of a WebAuthn credential by PUT'ting the ID and name of the authenticator representing that credential. You can obtain the credentials via the \"List authenticators\" endpoint.
    async fn allauth_account_authenticators_webauthn_put(
        &self,
        params: AllauthAccountAuthenticatorsWebauthnPutParams,
    ) -> Result<
        models::AllauthAccountAuthenticatorsWebauthnPut200Response,
        Error<AllauthAccountAuthenticatorsWebauthnPutError>,
    > {
        let AllauthAccountAuthenticatorsWebauthnPutParams {
            allauth_account_authenticators_webauthn_put_request,
        } = params;

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!(
            "{}/api/auth/v1/account/authenticators/webauthn",
            local_var_configuration.base_path
        );
        let mut local_var_req_builder =
            local_var_client.request(reqwest::Method::PUT, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder
                .header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder =
            local_var_req_builder.json(&allauth_account_authenticators_webauthn_put_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AllauthAccountAuthenticatorsWebauthnPut200Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AllauthAccountAuthenticatorsWebauthnPut200Response`")))),
            }
        } else {
            let local_var_entity: Option<AllauthAccountAuthenticatorsWebauthnPutError> =
                serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent {
                status: local_var_status,
                content: local_var_content,
                entity: local_var_entity,
            };
            Err(Error::ResponseError(local_var_error))
        }
    }
}

/// struct for typed errors of method [`AccountWebAuthnApi::allauth_account_authenticators_webauthn_delete`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllauthAccountAuthenticatorsWebauthnDeleteError {
    Status401(models::AllauthReauthenticationResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AccountWebAuthnApi::allauth_account_authenticators_webauthn_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllauthAccountAuthenticatorsWebauthnGetError {
    Status401(models::AllauthReauthenticationResponse),
    Status409(models::AllauthConflictResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AccountWebAuthnApi::allauth_account_authenticators_webauthn_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllauthAccountAuthenticatorsWebauthnPostError {
    Status401(models::AllauthReauthenticationResponse),
    Status409(models::AllauthConflictResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AccountWebAuthnApi::allauth_account_authenticators_webauthn_put`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllauthAccountAuthenticatorsWebauthnPutError {
    Status401(models::AllauthReauthenticationResponse),
    UnknownValue(serde_json::Value),
}
