/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */


use async_trait::async_trait;
use reqwest;
use std::sync::Arc;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};
use crate::apis::ContentType;

#[async_trait]
pub trait AuthenticationLoginByCodeApi: Send + Sync {

    /// POST /api/auth/v1/auth/code/confirm
    ///
    /// Use this endpoint to pass along the received \"special\" login code. 
    async fn allauth_auth_code_confirm_post(&self,  params: AllauthAuthCodeConfirmPostParams ) -> Result<models::AllauthAuthenticatedResponse, Error<AllauthAuthCodeConfirmPostError>>;

    /// POST /api/auth/v1/auth/code/request
    ///
    /// Request a \"special\" login code that is sent to the user by email. 
    async fn allauth_auth_code_request_post(&self,  params: AllauthAuthCodeRequestPostParams ) -> Result<(), Error<AllauthAuthCodeRequestPostError>>;
}

pub struct AuthenticationLoginByCodeApiClient {
    configuration: Arc<configuration::Configuration>
}

impl AuthenticationLoginByCodeApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}


/// struct for passing parameters to the method [`AuthenticationLoginByCodeApi::allauth_auth_code_confirm_post`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder), builder(finish_fn = build_struct))]
pub struct AllauthAuthCodeConfirmPostParams {
    pub allauth_confirm_login_code: models::AllauthConfirmLoginCode
}

/// struct for passing parameters to the method [`AuthenticationLoginByCodeApi::allauth_auth_code_request_post`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder), builder(finish_fn = build_struct))]
pub struct AllauthAuthCodeRequestPostParams {
    /// Request a login code.
    pub allauth_request_login_code: models::AllauthRequestLoginCode
}


#[async_trait]
impl AuthenticationLoginByCodeApi for AuthenticationLoginByCodeApiClient {
    /// Use this endpoint to pass along the received \"special\" login code. 
    async fn allauth_auth_code_confirm_post(&self,  params: AllauthAuthCodeConfirmPostParams ) -> Result<models::AllauthAuthenticatedResponse, Error<AllauthAuthCodeConfirmPostError>> {
        
        let AllauthAuthCodeConfirmPostParams {
            allauth_confirm_login_code,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/auth/v1/auth/code/confirm", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder = local_var_req_builder.json(&allauth_confirm_login_code);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AllauthAuthenticatedResponse`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AllauthAuthenticatedResponse`")))),
            }
        } else {
            let local_var_entity: Option<AllauthAuthCodeConfirmPostError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Request a \"special\" login code that is sent to the user by email. 
    async fn allauth_auth_code_request_post(&self,  params: AllauthAuthCodeRequestPostParams ) -> Result<(), Error<AllauthAuthCodeRequestPostError>> {
        
        let AllauthAuthCodeRequestPostParams {
            allauth_request_login_code,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/auth/v1/auth/code/request", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder = local_var_req_builder.json(&allauth_request_login_code);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            Ok(())
        } else {
            let local_var_entity: Option<AllauthAuthCodeRequestPostError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

}

/// struct for typed errors of method [`AuthenticationLoginByCodeApi::allauth_auth_code_confirm_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllauthAuthCodeConfirmPostError {
    Status400(models::AllauthErrorResponse),
    Status401(models::AllauthAuthenticationResponse),
    Status409(models::AllauthConflictResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AuthenticationLoginByCodeApi::allauth_auth_code_request_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllauthAuthCodeRequestPostError {
    Status400(models::AllauthErrorResponse),
    Status401(models::AllauthAuthenticationResponse),
    UnknownValue(serde_json::Value),
}

