/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */


use async_trait::async_trait;
use reqwest;
use std::sync::Arc;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};
use crate::apis::ContentType;

#[async_trait]
pub trait AuthenticationAccountApi: Send + Sync {

    /// GET /api/auth/v1/auth/email/verify
    ///
    /// Obtain email verification information, given the token that was sent to the user by email. 
    async fn allauth_auth_email_verify_get(&self,  params: AllauthAuthEmailVerifyGetParams ) -> Result<models::AllauthEmailVerificationInfo, Error<AllauthAuthEmailVerifyGetError>>;

    /// POST /api/auth/v1/auth/email/verify
    ///
    /// Complete the email verification process. Depending on the configuration, email addresses are either verified by opening a link that is sent to their email address, or, by inputting a code that is sent. On the API, both cases are handled identically. Meaning, the required key is either the one from the link, or, the code itself.  Note that a status code of 401 does not imply failure. It indicates that the email verification was successful, yet, the user is still not signed in. For example, in case `ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION` is set to `False`, a 401 is returned when verifying as part of login/signup. 
    async fn allauth_auth_email_verify_post(&self,  params: AllauthAuthEmailVerifyPostParams ) -> Result<models::AllauthAuthenticatedResponse, Error<AllauthAuthEmailVerifyPostError>>;

    /// POST /api/auth/v1/auth/email/verify/resend
    ///
    /// Requests a new email verification code. Requires `ACCOUNT_EMAIL_VERIFICATION_SUPPORTS_RESEND = True`. 
    async fn allauth_auth_email_verify_resend_post(&self, ) -> Result<models::AllauthAuthEmailVerifyResendPost200Response, Error<AllauthAuthEmailVerifyResendPostError>>;

    /// POST /api/auth/v1/auth/login
    ///
    /// Login using a username-password or email-password combination. 
    async fn allauth_auth_login_post(&self,  params: AllauthAuthLoginPostParams ) -> Result<models::AllauthAuthenticatedResponse, Error<AllauthAuthLoginPostError>>;

    /// POST /api/auth/v1/auth/phone/verify
    ///
    /// Complete the phone number verification process. Note that a status code of 401 does not imply failure. It merely indicates that the phone number verification was successful, yet, the user is still not signed in. 
    async fn allauth_auth_phone_verify_post(&self,  params: AllauthAuthPhoneVerifyPostParams ) -> Result<models::AllauthAuthenticatedResponse, Error<AllauthAuthPhoneVerifyPostError>>;

    /// POST /api/auth/v1/auth/phone/verify/resend
    ///
    /// Requests a new phone number verification code. Requires `ACCOUNT_PHONE_VERIFICATION_SUPPORTS_RESEND = True`. 
    async fn allauth_auth_phone_verify_resend_post(&self, ) -> Result<models::AllauthAuthEmailVerifyResendPost200Response, Error<AllauthAuthPhoneVerifyResendPostError>>;

    /// POST /api/auth/v1/auth/reauthenticate
    ///
    /// In order to safeguard the account, some actions require the user to be recently authenticated.  If you try to perform such an action without having been recently authenticated, a `401` status is returned, listing flows that can be performed to reauthenticate. One such flow is the flow with ID `reauthenticate`, which allows for the user to input the password. This is the endpoint related towards that flow. 
    async fn allauth_auth_reauthenticate_post(&self,  params: AllauthAuthReauthenticatePostParams ) -> Result<models::AllauthAuthenticatedResponse, Error<AllauthAuthReauthenticatePostError>>;

    /// POST /api/auth/v1/auth/signup
    ///
    /// Whether or not `username`, `email`, `phone` or combination of those are required depends on the configuration of django-allauth. Additionally, if a custom signup form is used there may be other custom properties required. 
    async fn allauth_auth_signup_post(&self,  params: AllauthAuthSignupPostParams ) -> Result<models::AllauthAuthenticatedResponse, Error<AllauthAuthSignupPostError>>;
}

pub struct AuthenticationAccountApiClient {
    configuration: Arc<configuration::Configuration>
}

impl AuthenticationAccountApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}


/// struct for passing parameters to the method [`AuthenticationAccountApi::allauth_auth_email_verify_get`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder), builder(finish_fn = build_struct))]
pub struct AllauthAuthEmailVerifyGetParams {
    /// The email verification key
    pub x_email_verification_key: String
}

/// struct for passing parameters to the method [`AuthenticationAccountApi::allauth_auth_email_verify_post`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder), builder(finish_fn = build_struct))]
pub struct AllauthAuthEmailVerifyPostParams {
    pub allauth_verify_email: Option<models::AllauthVerifyEmail>
}

/// struct for passing parameters to the method [`AuthenticationAccountApi::allauth_auth_login_post`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder), builder(finish_fn = build_struct))]
pub struct AllauthAuthLoginPostParams {
    /// Login.
    pub allauth_login: models::AllauthLogin
}

/// struct for passing parameters to the method [`AuthenticationAccountApi::allauth_auth_phone_verify_post`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder), builder(finish_fn = build_struct))]
pub struct AllauthAuthPhoneVerifyPostParams {
    pub allauth_verify_phone: Option<models::AllauthVerifyPhone>
}

/// struct for passing parameters to the method [`AuthenticationAccountApi::allauth_auth_reauthenticate_post`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder), builder(finish_fn = build_struct))]
pub struct AllauthAuthReauthenticatePostParams {
    /// Reauthenticate.
    pub allauth_reauthenticate: models::AllauthReauthenticate
}

/// struct for passing parameters to the method [`AuthenticationAccountApi::allauth_auth_signup_post`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder), builder(finish_fn = build_struct))]
pub struct AllauthAuthSignupPostParams {
    /// Signup
    pub allauth_signup: models::AllauthSignup
}


#[async_trait]
impl AuthenticationAccountApi for AuthenticationAccountApiClient {
    /// Obtain email verification information, given the token that was sent to the user by email. 
    async fn allauth_auth_email_verify_get(&self,  params: AllauthAuthEmailVerifyGetParams ) -> Result<models::AllauthEmailVerificationInfo, Error<AllauthAuthEmailVerifyGetError>> {
        
        let AllauthAuthEmailVerifyGetParams {
            x_email_verification_key,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/auth/v1/auth/email/verify", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder = local_var_req_builder.header("X-Email-Verification-Key", x_email_verification_key.to_string());

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AllauthEmailVerificationInfo`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AllauthEmailVerificationInfo`")))),
            }
        } else {
            let local_var_entity: Option<AllauthAuthEmailVerifyGetError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Complete the email verification process. Depending on the configuration, email addresses are either verified by opening a link that is sent to their email address, or, by inputting a code that is sent. On the API, both cases are handled identically. Meaning, the required key is either the one from the link, or, the code itself.  Note that a status code of 401 does not imply failure. It indicates that the email verification was successful, yet, the user is still not signed in. For example, in case `ACCOUNT_LOGIN_ON_EMAIL_CONFIRMATION` is set to `False`, a 401 is returned when verifying as part of login/signup. 
    async fn allauth_auth_email_verify_post(&self,  params: AllauthAuthEmailVerifyPostParams ) -> Result<models::AllauthAuthenticatedResponse, Error<AllauthAuthEmailVerifyPostError>> {
        
        let AllauthAuthEmailVerifyPostParams {
            allauth_verify_email,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/auth/v1/auth/email/verify", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder = local_var_req_builder.json(&allauth_verify_email);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AllauthAuthenticatedResponse`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AllauthAuthenticatedResponse`")))),
            }
        } else {
            let local_var_entity: Option<AllauthAuthEmailVerifyPostError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Requests a new email verification code. Requires `ACCOUNT_EMAIL_VERIFICATION_SUPPORTS_RESEND = True`. 
    async fn allauth_auth_email_verify_resend_post(&self, ) -> Result<models::AllauthAuthEmailVerifyResendPost200Response, Error<AllauthAuthEmailVerifyResendPostError>> {
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/auth/v1/auth/email/verify/resend", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AllauthAuthEmailVerifyResendPost200Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AllauthAuthEmailVerifyResendPost200Response`")))),
            }
        } else {
            let local_var_entity: Option<AllauthAuthEmailVerifyResendPostError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Login using a username-password or email-password combination. 
    async fn allauth_auth_login_post(&self,  params: AllauthAuthLoginPostParams ) -> Result<models::AllauthAuthenticatedResponse, Error<AllauthAuthLoginPostError>> {
        
        let AllauthAuthLoginPostParams {
            allauth_login,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/auth/v1/auth/login", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder = local_var_req_builder.json(&allauth_login);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AllauthAuthenticatedResponse`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AllauthAuthenticatedResponse`")))),
            }
        } else {
            let local_var_entity: Option<AllauthAuthLoginPostError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Complete the phone number verification process. Note that a status code of 401 does not imply failure. It merely indicates that the phone number verification was successful, yet, the user is still not signed in. 
    async fn allauth_auth_phone_verify_post(&self,  params: AllauthAuthPhoneVerifyPostParams ) -> Result<models::AllauthAuthenticatedResponse, Error<AllauthAuthPhoneVerifyPostError>> {
        
        let AllauthAuthPhoneVerifyPostParams {
            allauth_verify_phone,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/auth/v1/auth/phone/verify", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder = local_var_req_builder.json(&allauth_verify_phone);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AllauthAuthenticatedResponse`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AllauthAuthenticatedResponse`")))),
            }
        } else {
            let local_var_entity: Option<AllauthAuthPhoneVerifyPostError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Requests a new phone number verification code. Requires `ACCOUNT_PHONE_VERIFICATION_SUPPORTS_RESEND = True`. 
    async fn allauth_auth_phone_verify_resend_post(&self, ) -> Result<models::AllauthAuthEmailVerifyResendPost200Response, Error<AllauthAuthPhoneVerifyResendPostError>> {
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/auth/v1/auth/phone/verify/resend", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AllauthAuthEmailVerifyResendPost200Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AllauthAuthEmailVerifyResendPost200Response`")))),
            }
        } else {
            let local_var_entity: Option<AllauthAuthPhoneVerifyResendPostError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// In order to safeguard the account, some actions require the user to be recently authenticated.  If you try to perform such an action without having been recently authenticated, a `401` status is returned, listing flows that can be performed to reauthenticate. One such flow is the flow with ID `reauthenticate`, which allows for the user to input the password. This is the endpoint related towards that flow. 
    async fn allauth_auth_reauthenticate_post(&self,  params: AllauthAuthReauthenticatePostParams ) -> Result<models::AllauthAuthenticatedResponse, Error<AllauthAuthReauthenticatePostError>> {
        
        let AllauthAuthReauthenticatePostParams {
            allauth_reauthenticate,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/auth/v1/auth/reauthenticate", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder = local_var_req_builder.json(&allauth_reauthenticate);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AllauthAuthenticatedResponse`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AllauthAuthenticatedResponse`")))),
            }
        } else {
            let local_var_entity: Option<AllauthAuthReauthenticatePostError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

    /// Whether or not `username`, `email`, `phone` or combination of those are required depends on the configuration of django-allauth. Additionally, if a custom signup form is used there may be other custom properties required. 
    async fn allauth_auth_signup_post(&self,  params: AllauthAuthSignupPostParams ) -> Result<models::AllauthAuthenticatedResponse, Error<AllauthAuthSignupPostError>> {
        
        let AllauthAuthSignupPostParams {
            allauth_signup,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/auth/v1/auth/signup", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::POST, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder = local_var_req_builder.json(&allauth_signup);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AllauthAuthenticatedResponse`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AllauthAuthenticatedResponse`")))),
            }
        } else {
            let local_var_entity: Option<AllauthAuthSignupPostError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

}

/// struct for typed errors of method [`AuthenticationAccountApi::allauth_auth_email_verify_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllauthAuthEmailVerifyGetError {
    Status400(models::AllauthErrorResponse),
    Status409(models::AllauthConflictResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AuthenticationAccountApi::allauth_auth_email_verify_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllauthAuthEmailVerifyPostError {
    Status400(models::AllauthErrorResponse),
    Status401(models::AllauthAuthenticationResponse),
    Status409(models::AllauthConflictResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AuthenticationAccountApi::allauth_auth_email_verify_resend_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllauthAuthEmailVerifyResendPostError {
    Status409(models::AllauthConflictResponse),
    Status429(models::AllauthAuthEmailVerifyResendPost429Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AuthenticationAccountApi::allauth_auth_login_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllauthAuthLoginPostError {
    Status400(models::AllauthErrorResponse),
    Status401(models::AllauthAuthenticationResponse),
    Status409(models::AllauthConflictResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AuthenticationAccountApi::allauth_auth_phone_verify_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllauthAuthPhoneVerifyPostError {
    Status400(models::AllauthErrorResponse),
    Status401(models::AllauthAuthenticationResponse),
    Status409(models::AllauthConflictResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AuthenticationAccountApi::allauth_auth_phone_verify_resend_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllauthAuthPhoneVerifyResendPostError {
    Status409(models::AllauthConflictResponse),
    Status429(models::AllauthAuthEmailVerifyResendPost429Response),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AuthenticationAccountApi::allauth_auth_reauthenticate_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllauthAuthReauthenticatePostError {
    Status400(models::AllauthErrorResponse),
    UnknownValue(serde_json::Value),
}

/// struct for typed errors of method [`AuthenticationAccountApi::allauth_auth_signup_post`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllauthAuthSignupPostError {
    Status400(models::AllauthErrorResponse),
    Status401(models::AllauthAuthenticationResponse),
    Status403(models::AllauthForbiddenResponse),
    Status409(models::AllauthConflictResponse),
    UnknownValue(serde_json::Value),
}

