/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */


use async_trait::async_trait;
use reqwest;
use std::sync::Arc;
use serde::{Deserialize, Serialize, de::Error as _};
use crate::{apis::ResponseContent, models};
use super::{Error, configuration};
use crate::apis::ContentType;

#[async_trait]
pub trait TokensApi: Send + Sync {

    /// GET /api/auth/v1/tokens/refresh
    ///
    /// Used to retrieve a new access token. Depending on `settings.HEADLESS_JWT_ROTATE_REFRESH_TOKEN`, a new refresh token is returned as well. 
    async fn allauth_tokens_refresh_get(&self,  params: AllauthTokensRefreshGetParams ) -> Result<models::AllauthTokensRefreshGet200Response, Error<AllauthTokensRefreshGetError>>;
}

pub struct TokensApiClient {
    configuration: Arc<configuration::Configuration>
}

impl TokensApiClient {
    pub fn new(configuration: Arc<configuration::Configuration>) -> Self {
        Self { configuration }
    }
}


/// struct for passing parameters to the method [`TokensApi::allauth_tokens_refresh_get`]
#[derive(Clone, Debug)]
#[cfg_attr(feature = "bon", derive(::bon::Builder), builder(finish_fn = build_struct))]
pub struct AllauthTokensRefreshGetParams {
    pub allauth_tokens_refresh_get_request: Option<models::AllauthTokensRefreshGetRequest>
}


#[async_trait]
impl TokensApi for TokensApiClient {
    /// Used to retrieve a new access token. Depending on `settings.HEADLESS_JWT_ROTATE_REFRESH_TOKEN`, a new refresh token is returned as well. 
    async fn allauth_tokens_refresh_get(&self,  params: AllauthTokensRefreshGetParams ) -> Result<models::AllauthTokensRefreshGet200Response, Error<AllauthTokensRefreshGetError>> {
        
        let AllauthTokensRefreshGetParams {
            allauth_tokens_refresh_get_request,
        } = params;
        

        let local_var_configuration = &self.configuration;

        let local_var_client = &local_var_configuration.client;

        let local_var_uri_str = format!("{}/api/auth/v1/tokens/refresh", local_var_configuration.base_path);
        let mut local_var_req_builder = local_var_client.request(reqwest::Method::GET, local_var_uri_str.as_str());

        if let Some(ref local_var_user_agent) = local_var_configuration.user_agent {
            local_var_req_builder = local_var_req_builder.header(reqwest::header::USER_AGENT, local_var_user_agent.clone());
        }
        local_var_req_builder = local_var_req_builder.json(&allauth_tokens_refresh_get_request);

        let local_var_req = local_var_req_builder.build()?;
        let local_var_resp = local_var_client.execute(local_var_req).await?;

        let local_var_status = local_var_resp.status();
        let local_var_content_type = local_var_resp
            .headers()
            .get("content-type")
            .and_then(|v| v.to_str().ok())
            .unwrap_or("application/octet-stream");
        let local_var_content_type = super::ContentType::from(local_var_content_type);
        let local_var_content = local_var_resp.text().await?;

        if !local_var_status.is_client_error() && !local_var_status.is_server_error() {
            match local_var_content_type {
                ContentType::Json => serde_json::from_str(&local_var_content).map_err(Error::from),
                ContentType::Text => return Err(Error::from(serde_json::Error::custom("Received `text/plain` content type response that cannot be converted to `models::AllauthTokensRefreshGet200Response`"))),
                ContentType::Unsupported(local_var_unknown_type) => return Err(Error::from(serde_json::Error::custom(format!("Received `{local_var_unknown_type}` content type response that cannot be converted to `models::AllauthTokensRefreshGet200Response`")))),
            }
        } else {
            let local_var_entity: Option<AllauthTokensRefreshGetError> = serde_json::from_str(&local_var_content).ok();
            let local_var_error = ResponseContent { status: local_var_status, content: local_var_content, entity: local_var_entity };
            Err(Error::ResponseError(local_var_error))
        }
    }

}

/// struct for typed errors of method [`TokensApi::allauth_tokens_refresh_get`]
#[derive(Debug, Clone, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllauthTokensRefreshGetError {
    Status400(models::AllauthErrorResponse),
    UnknownValue(serde_json::Value),
}

