/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ActionPlugin : Serializer for the ActionPluginView responses.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ActionPlugin {
    #[serde(rename = "action")]
    pub action: String,
    #[serde(rename = "data")]
    pub data: std::collections::HashMap<String, serde_json::Value>,
}

impl ActionPlugin {
    /// Serializer for the ActionPluginView responses.
    pub fn new(action: String, data: std::collections::HashMap<String, serde_json::Value>) -> ActionPlugin {
        ActionPlugin {
            action,
            data,
        }
    }
}

