/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllauthAccountAuthenticatorsTotpGet200Response {
    #[serde(rename = "status")]
    pub status: models::AllauthStatusOk,
    #[serde(rename = "meta", skip_serializing_if = "Option::is_none")]
    pub meta: Option<Box<models::AllauthAccountAuthenticatorsTotpGet200ResponseMeta>>,
    #[serde(rename = "data")]
    pub data: Box<models::AllauthTotpAuthenticator>,
}

impl AllauthAccountAuthenticatorsTotpGet200Response {
    pub fn new(status: models::AllauthStatusOk, data: models::AllauthTotpAuthenticator) -> AllauthAccountAuthenticatorsTotpGet200Response {
        AllauthAccountAuthenticatorsTotpGet200Response {
            status,
            meta: None,
            data: Box::new(data),
        }
    }
}

