/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllauthWebAuthnAuthenticator {
    /// An epoch based timestamp (trivial to parse using: `new Date(value)*1000`)
    #[serde(rename = "last_used_at")]
    pub last_used_at: f64,
    /// An epoch based timestamp (trivial to parse using: `new Date(value)*1000`)
    #[serde(rename = "created_at")]
    pub created_at: f64,
    #[serde(rename = "type")]
    pub r#type: models::AllauthWebAuthnAuthenticatorTypeEnum,
    /// Authenticator ID.
    #[serde(rename = "id")]
    pub id: i32,
    #[serde(rename = "name")]
    pub name: String,
    /// Whether or not this authenticator represents a passkey. Absent if it is not specified.
    #[serde(rename = "is_passwordless", skip_serializing_if = "Option::is_none")]
    pub is_passwordless: Option<bool>,
}

impl AllauthWebAuthnAuthenticator {
    pub fn new(
        last_used_at: f64,
        created_at: f64,
        r#type: models::AllauthWebAuthnAuthenticatorTypeEnum,
        id: i32,
        name: String,
    ) -> AllauthWebAuthnAuthenticator {
        AllauthWebAuthnAuthenticator {
            last_used_at,
            created_at,
            r#type,
            id,
            name,
            is_passwordless: None,
        }
    }
}
