/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// AllauthSessionGoneResponse : The session is expired or invalid.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllauthSessionGoneResponse {
    #[serde(rename = "status")]
    pub status: models::AllauthSessionGoneResponseStatusEnum,
    #[serde(rename = "data")]
    pub data: serde_json::Value,
    #[serde(rename = "meta")]
    pub meta: Box<models::AllauthAuthenticationMeta>,
}

impl AllauthSessionGoneResponse {
    /// The session is expired or invalid.
    pub fn new(
        status: models::AllauthSessionGoneResponseStatusEnum,
        data: serde_json::Value,
        meta: models::AllauthAuthenticationMeta,
    ) -> AllauthSessionGoneResponse {
        AllauthSessionGoneResponse {
            status,
            data,
            meta: Box::new(meta),
        }
    }
}
