/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllauthAccountAuthenticatorsTotpGet404ResponseMeta {
    /// A TOTP secret that can be used to setup a new authenticator.
    #[serde(rename = "secret")]
    pub secret: String,
    /// otpauth URI from which a QR code can be generated and scanned by OTP clients.
    #[serde(rename = "totp_url")]
    pub totp_url: String,
}

impl AllauthAccountAuthenticatorsTotpGet404ResponseMeta {
    pub fn new(
        secret: String,
        totp_url: String,
    ) -> AllauthAccountAuthenticatorsTotpGet404ResponseMeta {
        AllauthAccountAuthenticatorsTotpGet404ResponseMeta { secret, totp_url }
    }
}
