/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllauthAccountAuthenticatorsWebauthnPost200ResponseMeta {
    /// Whether or not recovery codes where generated automatically.
    #[serde(
        rename = "recovery_codes_generated",
        skip_serializing_if = "Option::is_none"
    )]
    pub recovery_codes_generated: Option<bool>,
}

impl AllauthAccountAuthenticatorsWebauthnPost200ResponseMeta {
    pub fn new() -> AllauthAccountAuthenticatorsWebauthnPost200ResponseMeta {
        AllauthAccountAuthenticatorsWebauthnPost200ResponseMeta {
            recovery_codes_generated: None,
        }
    }
}
