/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllauthAuthenticatorListInner {
    AllauthTotpAuthenticator(Box<models::AllauthTotpAuthenticator>),
    AllauthRecoveryCodesAuthenticator(Box<models::AllauthRecoveryCodesAuthenticator>),
    AllauthWebAuthnAuthenticator(Box<models::AllauthWebAuthnAuthenticator>),
}

impl Default for AllauthAuthenticatorListInner {
    fn default() -> Self {
        Self::AllauthTotpAuthenticator(Default::default())
    }
}
