/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

use serde_repr::{Deserialize_repr, Serialize_repr};
///
#[repr(i64)]
#[derive(
    Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize_repr, Deserialize_repr,
)]
pub enum AllauthSessionGoneResponseStatusEnum {
    Variant410 = 410,
}

impl std::fmt::Display for AllauthSessionGoneResponseStatusEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(
            f,
            "{}",
            match self {
                Self::Variant410 => "410",
            }
        )
    }
}
impl Default for AllauthSessionGoneResponseStatusEnum {
    fn default() -> AllauthSessionGoneResponseStatusEnum {
        Self::Variant410
    }
}
