/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Serialize, Deserialize)]
#[serde(untagged)]
pub enum AllauthAuthenticationMethod {
    AuthenticatedByUsernameEmailLogin(Box<models::AuthenticatedByUsernameEmailLogin>),
    AuthenticatedAfterPasswordReset(Box<models::AuthenticatedAfterPasswordReset>),
    AuthenticatedByConfirmingACodeSentByEmail(Box<models::AuthenticatedByConfirmingACodeSentByEmail>),
    AuthenticatedByConfirmingACodeSentByPhone(Box<models::AuthenticatedByConfirmingACodeSentByPhone>),
    ReauthenticatedByPassword(Box<models::ReauthenticatedByPassword>),
    AuthenticatedByThirdPartyProvider(Box<models::AuthenticatedByThirdPartyProvider>),
    ReAuthenticatedBy2Fa(Box<models::ReAuthenticatedBy2Fa>),
}

impl Default for AllauthAuthenticationMethod {
    fn default() -> Self {
        Self::AuthenticatedByUsernameEmailLogin(Default::default())
    }
}

