/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllauthAccountPhonePostRequest {
    #[serde(rename = "phone")]
    pub phone: String,
}

impl AllauthAccountPhonePostRequest {
    pub fn new(phone: String) -> AllauthAccountPhonePostRequest {
        AllauthAccountPhonePostRequest { phone }
    }
}
