/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllauthBaseAuthenticationMeta {
    /// The session token (`app` clients only).
    #[serde(rename = "session_token", skip_serializing_if = "Option::is_none")]
    pub session_token: Option<String>,
    /// The access token (`app` clients only).
    #[serde(rename = "access_token", skip_serializing_if = "Option::is_none")]
    pub access_token: Option<String>,
}

impl AllauthBaseAuthenticationMeta {
    pub fn new() -> AllauthBaseAuthenticationMeta {
        AllauthBaseAuthenticationMeta {
            session_token: None,
            access_token: None,
        }
    }
}
