/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllauthAccountEmailPatchRequest {
    /// An email address.
    #[serde(rename = "email")]
    pub email: String,
    /// Primary flag.
    #[serde(rename = "primary")]
    pub primary: bool,
}

impl AllauthAccountEmailPatchRequest {
    pub fn new(email: String, primary: bool) -> AllauthAccountEmailPatchRequest {
        AllauthAccountEmailPatchRequest { email, primary }
    }
}
