/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AllauthEndSessions {
    /// The IDs of the sessions that are to be ended. 
    #[serde(rename = "sessions")]
    pub sessions: Vec<i32>,
}

impl AllauthEndSessions {
    pub fn new(sessions: Vec<i32>) -> AllauthEndSessions {
        AllauthEndSessions {
            sessions,
        }
    }
}

