/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ApiSearchView : Serializer for the APISearchView.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ApiSearchView {
    #[serde(rename = "search")]
    pub search: String,
    #[serde(rename = "search_regex", skip_serializing_if = "Option::is_none")]
    pub search_regex: Option<bool>,
    #[serde(rename = "search_whole", skip_serializing_if = "Option::is_none")]
    pub search_whole: Option<bool>,
    #[serde(rename = "search_notes", skip_serializing_if = "Option::is_none")]
    pub search_notes: Option<bool>,
    #[serde(rename = "limit", skip_serializing_if = "Option::is_none")]
    pub limit: Option<i32>,
    #[serde(rename = "offset", skip_serializing_if = "Option::is_none")]
    pub offset: Option<i32>,
}

impl ApiSearchView {
    /// Serializer for the APISearchView.
    pub fn new(search: String) -> ApiSearchView {
        ApiSearchView {
            search,
            search_regex: None,
            search_whole: None,
            search_notes: None,
            limit: None,
            offset: None,
        }
    }
}
