/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct AuthenticatedByConfirmingACodeSentByPhone {
    #[serde(rename = "method")]
    pub method: models::AllauthAuthenticationMethodMethodEnum,
    /// An epoch based timestamp (trivial to parse using: `new Date(value)*1000`)
    #[serde(rename = "at")]
    pub at: f64,
    /// The phone number.
    #[serde(rename = "phone")]
    pub phone: String,
}

impl AuthenticatedByConfirmingACodeSentByPhone {
    pub fn new(
        method: models::AllauthAuthenticationMethodMethodEnum,
        at: f64,
        phone: String,
    ) -> AuthenticatedByConfirmingACodeSentByPhone {
        AuthenticatedByConfirmingACodeSentByPhone { method, at, phone }
    }
}
