/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BuildItem : Serializes a BuildItem object, which is an allocation of a stock item against a build order.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildItem {
    #[serde(rename = "pk")]
    pub pk: i32,
    #[serde(rename = "build")]
    pub build: i32,
    #[serde(rename = "build_line", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub build_line: Option<Option<i32>>,
    /// Destination stock item
    #[serde(rename = "install_into", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub install_into: Option<Option<i32>>,
    /// Source stock item
    #[serde(rename = "stock_item")]
    pub stock_item: i32,
    #[serde(rename = "quantity")]
    pub quantity: f64,
    #[serde(rename = "location")]
    pub location: i32,
    #[serde(rename = "build_detail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub build_detail: Option<Option<Box<models::Build>>>,
    #[serde(rename = "location_detail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub location_detail: Option<Option<Box<models::LocationBrief>>>,
    #[serde(rename = "part_detail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub part_detail: Option<Option<Box<models::PartBrief>>>,
    #[serde(rename = "stock_item_detail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub stock_item_detail: Option<Option<Box<models::StockItem>>>,
    #[serde(rename = "supplier_part_detail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub supplier_part_detail: Option<Option<Box<models::SupplierPart>>>,
    #[serde(rename = "install_into_detail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub install_into_detail: Option<Option<Box<models::StockItem>>>,
    #[serde(rename = "bom_reference")]
    pub bom_reference: String,
}

impl BuildItem {
    /// Serializes a BuildItem object, which is an allocation of a stock item against a build order.
    pub fn new(pk: i32, build: i32, stock_item: i32, quantity: f64, location: i32, bom_reference: String) -> BuildItem {
        BuildItem {
            pk,
            build,
            build_line: None,
            install_into: None,
            stock_item,
            quantity,
            location,
            build_detail: None,
            location_detail: None,
            part_detail: None,
            stock_item_detail: None,
            supplier_part_detail: None,
            install_into_detail: None,
            bom_reference,
        }
    }
}

