/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BuildAllocation : Serializer for allocating stock items against a build order.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildAllocation {
    #[serde(rename = "items")]
    pub items: Vec<models::BuildAllocationItem>,
}

impl BuildAllocation {
    /// Serializer for allocating stock items against a build order.
    pub fn new(items: Vec<models::BuildAllocationItem>) -> BuildAllocation {
        BuildAllocation { items }
    }
}
