/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// BuildConsumeAllocation : Serializer for an individual BuildItem to be consumed against a BuildOrder.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct BuildConsumeAllocation {
    #[serde(rename = "build_item")]
    pub build_item: i32,
    #[serde(rename = "quantity")]
    pub quantity: String,
}

impl BuildConsumeAllocation {
    /// Serializer for an individual BuildItem to be consumed against a BuildOrder.
    pub fn new(build_item: i32, quantity: String) -> BuildConsumeAllocation {
        BuildConsumeAllocation {
            build_item,
            quantity,
        }
    }
}
