/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ConfigTypeEnum : * `M` - Machine * `D` - Driver
/// * `M` - Machine * `D` - Driver
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ConfigTypeEnum {
    #[serde(rename = "M")]
    M,
    #[serde(rename = "D")]
    D,

}

impl std::fmt::Display for ConfigTypeEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::M => write!(f, "M"),
            Self::D => write!(f, "D"),
        }
    }
}

impl Default for ConfigTypeEnum {
    fn default() -> ConfigTypeEnum {
        Self::M
    }
}

