/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomUnit : DRF serializer for CustomUnit model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomUnit {
    #[serde(rename = "pk")]
    pub pk: i32,
    /// Unit name
    #[serde(rename = "name")]
    pub name: String,
    /// Optional unit symbol
    #[serde(rename = "symbol", skip_serializing_if = "Option::is_none")]
    pub symbol: Option<String>,
    /// Unit definition
    #[serde(rename = "definition")]
    pub definition: String,
}

impl CustomUnit {
    /// DRF serializer for CustomUnit model.
    pub fn new(pk: i32, name: String, definition: String) -> CustomUnit {
        CustomUnit {
            pk,
            name,
            symbol: None,
            definition,
        }
    }
}

