/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// CustomState : Serializer for the custom state model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct CustomState {
    #[serde(rename = "pk")]
    pub pk: i32,
    /// Numerical value that will be saved in the models database
    #[serde(rename = "key")]
    pub key: i64,
    /// Name of the state
    #[serde(rename = "name")]
    pub name: String,
    /// Label that will be displayed in the frontend
    #[serde(rename = "label")]
    pub label: String,
    /// Color that will be displayed in the frontend  * `primary` - primary * `secondary` - secondary * `success` - success * `danger` - danger * `warning` - warning * `info` - info * `dark` - dark
    #[serde(rename = "color", skip_serializing_if = "Option::is_none")]
    pub color: Option<models::ColorEnum>,
    /// State logical key that is equal to this custom state in business logic
    #[serde(rename = "logical_key")]
    pub logical_key: i64,
    /// Model this state is associated with
    #[serde(
        rename = "model",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub model: Option<Option<i32>>,
    #[serde(rename = "model_name")]
    pub model_name: String,
    #[serde(rename = "reference_status")]
    pub reference_status: models::ReferenceStatusEnum,
}

impl CustomState {
    /// Serializer for the custom state model.
    pub fn new(
        pk: i32,
        key: i64,
        name: String,
        label: String,
        logical_key: i64,
        model_name: String,
        reference_status: models::ReferenceStatusEnum,
    ) -> CustomState {
        CustomState {
            pk,
            key,
            name,
            label,
            color: None,
            logical_key,
            model: None,
            model_name,
            reference_status,
        }
    }
}
