/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// DirectionEnum : * `I` - Inbound * `O` - Outbound
/// * `I` - Inbound * `O` - Outbound
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum DirectionEnum {
    #[serde(rename = "I")]
    I,
    #[serde(rename = "O")]
    O,

}

impl std::fmt::Display for DirectionEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::I => write!(f, "I"),
            Self::O => write!(f, "O"),
        }
    }
}

impl Default for DirectionEnum {
    fn default() -> DirectionEnum {
        Self::I
    }
}

