/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ErrorMessage : DRF serializer for server error messages.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ErrorMessage {
    #[serde(rename = "when")]
    pub when: String,
    #[serde(rename = "info")]
    pub info: String,
    #[serde(rename = "data", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub data: Option<Option<String>>,
    #[serde(rename = "path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub path: Option<Option<String>>,
    #[serde(rename = "pk")]
    pub pk: i32,
}

impl ErrorMessage {
    /// DRF serializer for server error messages.
    pub fn new(when: String, info: String, pk: i32) -> ErrorMessage {
        ErrorMessage {
            when,
            info,
            data: None,
            path: None,
            pk,
        }
    }
}

