/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GenerateBatchCode : Serializer for generating a batch code.  Any of the provided write-only fields can be used for additional context.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenerateBatchCode {
    /// Generated batch code
    #[serde(rename = "batch_code")]
    pub batch_code: String,
    /// Select build order
    #[serde(rename = "build_order", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub build_order: Option<Option<i32>>,
    /// Select stock item to generate batch code for
    #[serde(rename = "item", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub item: Option<Option<i32>>,
    /// Select location to generate batch code for
    #[serde(rename = "location", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub location: Option<Option<i32>>,
    /// Select part to generate batch code for
    #[serde(rename = "part", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub part: Option<Option<i32>>,
    /// Select purchase order
    #[serde(rename = "purchase_order", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub purchase_order: Option<Option<i32>>,
    /// Enter quantity for batch code
    #[serde(rename = "quantity", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<Option<f64>>,
}

impl GenerateBatchCode {
    /// Serializer for generating a batch code.  Any of the provided write-only fields can be used for additional context.
    pub fn new(batch_code: String) -> GenerateBatchCode {
        GenerateBatchCode {
            batch_code,
            build_order: None,
            item: None,
            location: None,
            part: None,
            purchase_order: None,
            quantity: None,
        }
    }
}

