/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// GenericStateClass : API serializer for generic state class information.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct GenericStateClass {
    #[serde(rename = "status_class")]
    pub status_class: String,
    #[serde(rename = "values")]
    pub values: std::collections::HashMap<String, models::GenericStateValue>,
}

impl GenericStateClass {
    /// API serializer for generic state class information.
    pub fn new(status_class: String, values: std::collections::HashMap<String, models::GenericStateValue>) -> GenericStateClass {
        GenericStateClass {
            status_class,
            values,
        }
    }
}

