/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// HealthCheckStatusStatusEnum : * `ok` - ok * `loading` - loading
/// * `ok` - ok * `loading` - loading
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum HealthCheckStatusStatusEnum {
    #[serde(rename = "ok")]
    Ok,
    #[serde(rename = "loading")]
    Loading,

}

impl std::fmt::Display for HealthCheckStatusStatusEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Ok => write!(f, "ok"),
            Self::Loading => write!(f, "loading"),
        }
    }
}

impl Default for HealthCheckStatusStatusEnum {
    fn default() -> HealthCheckStatusStatusEnum {
        Self::Ok
    }
}

