/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// InfoApi : InvenTree server information - some information might be blanked if called without elevated credentials.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct InfoApi {
    #[serde(rename = "server")]
    pub server: String,
    #[serde(
        rename = "id",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub id: Option<Option<String>>,
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "instance")]
    pub instance: String,
    #[serde(rename = "apiVersion")]
    pub api_version: i32,
    #[serde(rename = "worker_running")]
    pub worker_running: bool,
    #[serde(rename = "worker_count")]
    pub worker_count: i32,
    #[serde(rename = "worker_pending_tasks")]
    pub worker_pending_tasks: i32,
    #[serde(rename = "plugins_enabled")]
    pub plugins_enabled: bool,
    #[serde(rename = "plugins_install_disabled")]
    pub plugins_install_disabled: bool,
    #[serde(rename = "active_plugins", deserialize_with = "Option::deserialize")]
    pub active_plugins: Option<serde_json::Value>,
    #[serde(rename = "email_configured")]
    pub email_configured: bool,
    #[serde(rename = "debug_mode")]
    pub debug_mode: bool,
    #[serde(rename = "docker_mode")]
    pub docker_mode: bool,
    #[serde(rename = "default_locale")]
    pub default_locale: String,
    #[serde(rename = "customize")]
    pub customize: Box<models::Customize>,
    #[serde(rename = "system_health")]
    pub system_health: bool,
    #[serde(rename = "database")]
    pub database: String,
    #[serde(rename = "platform")]
    pub platform: String,
    #[serde(rename = "installer")]
    pub installer: String,
    #[serde(
        rename = "target",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub target: Option<Option<String>>,
    #[serde(rename = "django_admin")]
    pub django_admin: String,
    #[serde(rename = "settings")]
    pub settings: Box<models::Settings>,
}

impl InfoApi {
    /// InvenTree server information - some information might be blanked if called without elevated credentials.
    pub fn new(
        server: String,
        version: String,
        instance: String,
        api_version: i32,
        worker_running: bool,
        worker_count: i32,
        worker_pending_tasks: i32,
        plugins_enabled: bool,
        plugins_install_disabled: bool,
        active_plugins: Option<serde_json::Value>,
        email_configured: bool,
        debug_mode: bool,
        docker_mode: bool,
        default_locale: String,
        customize: models::Customize,
        system_health: bool,
        database: String,
        platform: String,
        installer: String,
        django_admin: String,
        settings: models::Settings,
    ) -> InfoApi {
        InfoApi {
            server,
            id: None,
            version,
            instance,
            api_version,
            worker_running,
            worker_count,
            worker_pending_tasks,
            plugins_enabled,
            plugins_install_disabled,
            active_plugins,
            email_configured,
            debug_mode,
            docker_mode,
            default_locale,
            customize: Box::new(customize),
            system_health,
            database,
            platform,
            installer,
            target: None,
            django_admin,
            settings: Box::new(settings),
        }
    }
}
