/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// 
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum LoginMethodsEnum {
    #[serde(rename = "email")]
    Email,
    #[serde(rename = "username")]
    Username,

}

impl std::fmt::Display for LoginMethodsEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::Email => write!(f, "email"),
            Self::Username => write!(f, "username"),
        }
    }
}

impl Default for LoginMethodsEnum {
    fn default() -> LoginMethodsEnum {
        Self::Email
    }
}

