/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Nested {
    #[serde(rename = "id")]
    pub id: i32,
    /// JSON metadata field, for use by external plugins
    #[serde(rename = "metadata", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub metadata: Option<Option<serde_json::Value>>,
    /// Name
    #[serde(rename = "name")]
    pub name: String,
    /// Description (optional)
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Path
    #[serde(rename = "pathstring", skip_serializing_if = "Option::is_none")]
    pub pathstring: Option<String>,
    /// Parts may not be directly assigned to a structural category, but may be assigned to child categories.
    #[serde(rename = "structural", skip_serializing_if = "Option::is_none")]
    pub structural: Option<bool>,
    /// Default keywords for parts in this category
    #[serde(rename = "default_keywords", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default_keywords: Option<Option<String>>,
    /// Icon (optional)
    #[serde(rename = "_icon", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub _icon: Option<Option<String>>,
    #[serde(rename = "lft")]
    pub lft: i32,
    #[serde(rename = "rght")]
    pub rght: i32,
    #[serde(rename = "tree_id")]
    pub tree_id: i32,
    #[serde(rename = "level")]
    pub level: i32,
    #[serde(rename = "parent", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parent: Option<Option<i32>>,
    /// Default location for parts in this category
    #[serde(rename = "default_location", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default_location: Option<Option<i32>>,
}

impl Nested {
    pub fn new(id: i32, name: String, lft: i32, rght: i32, tree_id: i32, level: i32) -> Nested {
        Nested {
            id,
            metadata: None,
            name,
            description: None,
            pathstring: None,
            structural: None,
            default_keywords: None,
            _icon: None,
            lft,
            rght,
            tree_id,
            level,
            parent: None,
            default_location: None,
        }
    }
}

