/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ObservabilityEnd : Serializer for observability end endpoint.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ObservabilityEnd {
    /// Trace ID to end
    #[serde(rename = "traceid")]
    pub traceid: String,
    /// Service name
    #[serde(rename = "service")]
    pub service: String,
}

impl ObservabilityEnd {
    /// Serializer for observability end endpoint.
    pub fn new(traceid: String, service: String) -> ObservabilityEnd {
        ObservabilityEnd {
            traceid,
            service,
        }
    }
}

