/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PaginatedPluginSettingList {
    #[serde(rename = "count")]
    pub count: i32,
    #[serde(
        rename = "next",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub next: Option<Option<String>>,
    #[serde(
        rename = "previous",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub previous: Option<Option<String>>,
    #[serde(rename = "results")]
    pub results: Vec<models::PluginSetting>,
}

impl PaginatedPluginSettingList {
    pub fn new(count: i32, results: Vec<models::PluginSetting>) -> PaginatedPluginSettingList {
        PaginatedPluginSettingList {
            count,
            next: None,
            previous: None,
            results,
        }
    }
}
