/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartStocktakeGenerate : Serializer for generating PartStocktake entries.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartStocktakeGenerate {
    /// Select a part to generate stocktake information for that part (and any variant parts)
    #[serde(
        rename = "part",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub part: Option<Option<i32>>,
    /// Select a category to include all parts within that category (and subcategories)
    #[serde(
        rename = "category",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub category: Option<Option<i32>>,
    /// Select a location to include all parts with stock in that location (including sub-locations)
    #[serde(
        rename = "location",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub location: Option<Option<i32>>,
    /// Save stocktake entries for the selected parts
    #[serde(rename = "generate_entry", skip_serializing_if = "Option::is_none")]
    pub generate_entry: Option<bool>,
    /// Generate a stocktake report for the selected parts
    #[serde(rename = "generate_report", skip_serializing_if = "Option::is_none")]
    pub generate_report: Option<bool>,
    #[serde(rename = "output")]
    pub output: Box<models::DataOutput>,
}

impl PartStocktakeGenerate {
    /// Serializer for generating PartStocktake entries.
    pub fn new(output: models::DataOutput) -> PartStocktakeGenerate {
        PartStocktakeGenerate {
            part: None,
            category: None,
            location: None,
            generate_entry: None,
            generate_report: None,
            output: Box::new(output),
        }
    }
}
