/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartThumbSerializerUpdate : Serializer for updating Part thumbnail.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartThumbSerializerUpdate {
    #[serde(rename = "image")]
    pub image: String,
}

impl PartThumbSerializerUpdate {
    /// Serializer for updating Part thumbnail.
    pub fn new(image: String) -> PartThumbSerializerUpdate {
        PartThumbSerializerUpdate {
            image,
        }
    }
}

