/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartSerialNumber : Serializer for Part serial number information.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartSerialNumber {
    #[serde(rename = "latest", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub latest: Option<Option<String>>,
    #[serde(rename = "next")]
    pub next: String,
}

impl PartSerialNumber {
    /// Serializer for Part serial number information.
    pub fn new(next: String) -> PartSerialNumber {
        PartSerialNumber {
            latest: None,
            next,
        }
    }
}

