/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartStocktake : Serializer for the PartStocktake model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartStocktake {
    #[serde(rename = "pk")]
    pub pk: i32,
    /// Part for stocktake
    #[serde(rename = "part")]
    pub part: i32,
    #[serde(rename = "part_name")]
    pub part_name: String,
    #[serde(rename = "part_ipn", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub part_ipn: Option<Option<String>>,
    #[serde(rename = "part_description", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub part_description: Option<Option<String>>,
    /// Date stocktake was performed
    #[serde(rename = "date")]
    pub date: String,
    /// Number of individual stock entries at time of stocktake
    #[serde(rename = "item_count", skip_serializing_if = "Option::is_none")]
    pub item_count: Option<i32>,
    #[serde(rename = "quantity")]
    pub quantity: f64,
    #[serde(rename = "cost_min", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cost_min: Option<Option<String>>,
    /// Select currency from available options
    #[serde(rename = "cost_min_currency", skip_serializing_if = "Option::is_none")]
    pub cost_min_currency: Option<String>,
    #[serde(rename = "cost_max", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub cost_max: Option<Option<String>>,
    /// Select currency from available options
    #[serde(rename = "cost_max_currency", skip_serializing_if = "Option::is_none")]
    pub cost_max_currency: Option<String>,
}

impl PartStocktake {
    /// Serializer for the PartStocktake model.
    pub fn new(pk: i32, part: i32, part_name: String, date: String, quantity: f64) -> PartStocktake {
        PartStocktake {
            pk,
            part,
            part_name,
            part_ipn: None,
            part_description: None,
            date,
            item_count: None,
            quantity,
            cost_min: None,
            cost_min_currency: None,
            cost_max: None,
            cost_max_currency: None,
        }
    }
}

