/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Part : Serializer for complete detail information of a part.  Used when displaying all details of a single component.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Part {
    /// Is this part active?
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// Can this part be built from other parts?
    #[serde(rename = "assembly", skip_serializing_if = "Option::is_none")]
    pub assembly: Option<bool>,
    /// Unique hash of barcode data
    #[serde(rename = "barcode_hash")]
    pub barcode_hash: String,
    #[serde(rename = "category", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub category: Option<Option<i32>>,
    #[serde(rename = "category_detail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub category_detail: Option<Option<Box<models::Category>>>,
    #[serde(rename = "category_path", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub category_path: Option<Option<Vec<std::collections::HashMap<String, serde_json::Value>>>>,
    #[serde(rename = "category_name")]
    pub category_name: String,
    /// Can this part be used to build other parts?
    #[serde(rename = "component", skip_serializing_if = "Option::is_none")]
    pub component: Option<bool>,
    #[serde(rename = "creation_date", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub creation_date: Option<Option<String>>,
    #[serde(rename = "creation_user", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub creation_user: Option<Option<i32>>,
    /// Expiry time (in days) for stock items of this part
    #[serde(rename = "default_expiry", skip_serializing_if = "Option::is_none")]
    pub default_expiry: Option<u64>,
    /// Where is this item normally stored?
    #[serde(rename = "default_location", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default_location: Option<Option<i32>>,
    #[serde(rename = "default_location_detail", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default_location_detail: Option<Option<Box<models::DefaultLocation>>>,
    /// Default supplier part
    #[serde(rename = "default_supplier", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub default_supplier: Option<Option<i32>>,
    /// Part description (optional)
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Format a 'full name' for this Part based on the format PART_NAME_FORMAT defined in InvenTree settings.
    #[serde(rename = "full_name")]
    pub full_name: String,
    #[serde(rename = "image", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub image: Option<Option<String>>,
    /// URL of remote image file
    #[serde(rename = "remote_image", skip_serializing_if = "Option::is_none")]
    pub remote_image: Option<String>,
    /// Filename of an existing part image
    #[serde(rename = "existing_image", skip_serializing_if = "Option::is_none")]
    pub existing_image: Option<String>,
    #[serde(rename = "IPN", skip_serializing_if = "Option::is_none")]
    pub ipn: Option<String>,
    /// Is this part a template part?
    #[serde(rename = "is_template", skip_serializing_if = "Option::is_none")]
    pub is_template: Option<bool>,
    /// Part keywords to improve visibility in search results
    #[serde(rename = "keywords", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub keywords: Option<Option<String>>,
    /// Link to external URL
    #[serde(rename = "link", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub link: Option<Option<String>>,
    /// Locked parts cannot be edited
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<bool>,
    #[serde(rename = "minimum_stock", skip_serializing_if = "Option::is_none")]
    pub minimum_stock: Option<f64>,
    /// Part name
    #[serde(rename = "name")]
    pub name: String,
    /// Markdown notes (optional)
    #[serde(rename = "notes", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub notes: Option<Option<String>>,
    #[serde(rename = "parameters", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub parameters: Option<Option<Vec<models::Parameter>>>,
    #[serde(rename = "pk")]
    pub pk: i32,
    /// Can this part be purchased from external suppliers?
    #[serde(rename = "purchaseable", skip_serializing_if = "Option::is_none")]
    pub purchaseable: Option<bool>,
    #[serde(rename = "revision", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub revision: Option<Option<String>>,
    /// Is this part a revision of another part?
    #[serde(rename = "revision_of", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub revision_of: Option<Option<i32>>,
    #[serde(rename = "revision_count", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub revision_count: Option<Option<i32>>,
    /// Can this part be sold to customers?
    #[serde(rename = "salable", skip_serializing_if = "Option::is_none")]
    pub salable: Option<bool>,
    /// Return \"true\" if the part is starred by the current user.
    #[serde(rename = "starred")]
    pub starred: bool,
    #[serde(rename = "thumbnail")]
    pub thumbnail: String,
    /// Can this part have test results recorded against it?
    #[serde(rename = "testable", skip_serializing_if = "Option::is_none")]
    pub testable: Option<bool>,
    /// Does this part have tracking for unique items?
    #[serde(rename = "trackable", skip_serializing_if = "Option::is_none")]
    pub trackable: Option<bool>,
    /// Units of measure for this part
    #[serde(rename = "units", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub units: Option<Option<String>>,
    /// Is this part a variant of another part?
    #[serde(rename = "variant_of", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub variant_of: Option<Option<i32>>,
    /// Is this a virtual part, such as a software product or license?
    #[serde(rename = "virtual", skip_serializing_if = "Option::is_none")]
    pub r#virtual: Option<bool>,
    #[serde(rename = "pricing_min", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pricing_min: Option<Option<String>>,
    #[serde(rename = "pricing_max", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pricing_max: Option<Option<String>>,
    #[serde(rename = "pricing_updated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub pricing_updated: Option<Option<String>>,
    #[serde(rename = "responsible", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub responsible: Option<Option<i32>>,
    #[serde(rename = "price_breaks", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub price_breaks: Option<Option<Vec<models::PartSalePrice>>>,
    #[serde(rename = "allocated_to_build_orders", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allocated_to_build_orders: Option<Option<f64>>,
    #[serde(rename = "allocated_to_sales_orders", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub allocated_to_sales_orders: Option<Option<f64>>,
    /// Quantity of this part currently being in production
    #[serde(rename = "building", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub building: Option<Option<f64>>,
    /// Outstanding quantity of this part scheduled to be built
    #[serde(rename = "scheduled_to_build", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub scheduled_to_build: Option<Option<f64>>,
    #[serde(rename = "category_default_location", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub category_default_location: Option<Option<i32>>,
    #[serde(rename = "in_stock", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub in_stock: Option<Option<f64>>,
    #[serde(rename = "ordering", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub ordering: Option<Option<f64>>,
    #[serde(rename = "required_for_build_orders", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub required_for_build_orders: Option<Option<i32>>,
    #[serde(rename = "required_for_sales_orders", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub required_for_sales_orders: Option<Option<i32>>,
    #[serde(rename = "stock_item_count", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub stock_item_count: Option<Option<i32>>,
    #[serde(rename = "total_in_stock", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub total_in_stock: Option<Option<f64>>,
    #[serde(rename = "external_stock", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub external_stock: Option<Option<f64>>,
    #[serde(rename = "unallocated_stock", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub unallocated_stock: Option<Option<f64>>,
    #[serde(rename = "variant_stock", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub variant_stock: Option<Option<f64>>,
    /// Copy initial data from another Part
    #[serde(rename = "duplicate", skip_serializing_if = "Option::is_none")]
    pub duplicate: Option<Box<models::DuplicatePart>>,
    /// Create Part with initial stock quantity
    #[serde(rename = "initial_stock", skip_serializing_if = "Option::is_none")]
    pub initial_stock: Option<Box<models::InitialStock>>,
    /// Add initial supplier information for this part
    #[serde(rename = "initial_supplier", skip_serializing_if = "Option::is_none")]
    pub initial_supplier: Option<Box<models::InitialSupplier>>,
    /// Copy parameter templates from selected part category
    #[serde(rename = "copy_category_parameters", skip_serializing_if = "Option::is_none")]
    pub copy_category_parameters: Option<bool>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
}

impl Part {
    /// Serializer for complete detail information of a part.  Used when displaying all details of a single component.
    pub fn new(barcode_hash: String, category_name: String, full_name: String, name: String, pk: i32, starred: bool, thumbnail: String) -> Part {
        Part {
            active: None,
            assembly: None,
            barcode_hash,
            category: None,
            category_detail: None,
            category_path: None,
            category_name,
            component: None,
            creation_date: None,
            creation_user: None,
            default_expiry: None,
            default_location: None,
            default_location_detail: None,
            default_supplier: None,
            description: None,
            full_name,
            image: None,
            remote_image: None,
            existing_image: None,
            ipn: None,
            is_template: None,
            keywords: None,
            link: None,
            locked: None,
            minimum_stock: None,
            name,
            notes: None,
            parameters: None,
            pk,
            purchaseable: None,
            revision: None,
            revision_of: None,
            revision_count: None,
            salable: None,
            starred,
            thumbnail,
            testable: None,
            trackable: None,
            units: None,
            variant_of: None,
            r#virtual: None,
            pricing_min: None,
            pricing_max: None,
            pricing_updated: None,
            responsible: None,
            price_breaks: None,
            allocated_to_build_orders: None,
            allocated_to_sales_orders: None,
            building: None,
            scheduled_to_build: None,
            category_default_location: None,
            in_stock: None,
            ordering: None,
            required_for_build_orders: None,
            required_for_sales_orders: None,
            stock_item_count: None,
            total_in_stock: None,
            external_stock: None,
            unallocated_stock: None,
            variant_stock: None,
            duplicate: None,
            initial_stock: None,
            initial_supplier: None,
            copy_category_parameters: None,
            tags: None,
        }
    }
}

