/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PartRequirements : Serializer for Part requirements.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PartRequirements {
    #[serde(rename = "total_stock")]
    pub total_stock: f64,
    #[serde(rename = "unallocated_stock")]
    pub unallocated_stock: f64,
    #[serde(rename = "can_build")]
    pub can_build: f64,
    #[serde(rename = "ordering")]
    pub ordering: f64,
    #[serde(rename = "building")]
    pub building: f64,
    #[serde(rename = "scheduled_to_build")]
    pub scheduled_to_build: i32,
    #[serde(rename = "required_for_build_orders")]
    pub required_for_build_orders: f64,
    #[serde(rename = "allocated_to_build_orders")]
    pub allocated_to_build_orders: f64,
    #[serde(rename = "required_for_sales_orders")]
    pub required_for_sales_orders: f64,
    /// Return the allocated sales order quantity.
    #[serde(rename = "allocated_to_sales_orders")]
    pub allocated_to_sales_orders: f64,
}

impl PartRequirements {
    /// Serializer for Part requirements.
    pub fn new(
        total_stock: f64,
        unallocated_stock: f64,
        can_build: f64,
        ordering: f64,
        building: f64,
        scheduled_to_build: i32,
        required_for_build_orders: f64,
        allocated_to_build_orders: f64,
        required_for_sales_orders: f64,
        allocated_to_sales_orders: f64,
    ) -> PartRequirements {
        PartRequirements {
            total_stock,
            unallocated_stock,
            can_build,
            ordering,
            building,
            scheduled_to_build,
            required_for_build_orders,
            allocated_to_build_orders,
            required_for_sales_orders,
            allocated_to_sales_orders,
        }
    }
}
