/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatchedPartThumbSerializerUpdate : Serializer for updating Part thumbnail.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedPartThumbSerializerUpdate {
    #[serde(rename = "image", skip_serializing_if = "Option::is_none")]
    pub image: Option<String>,
}

impl PatchedPartThumbSerializerUpdate {
    /// Serializer for updating Part thumbnail.
    pub fn new() -> PatchedPartThumbSerializerUpdate {
        PatchedPartThumbSerializerUpdate {
            image: None,
        }
    }
}

