/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatchedUserSettings : Serializer for the InvenTreeUserSetting model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedUserSettings {
    #[serde(rename = "pk", skip_serializing_if = "Option::is_none")]
    pub pk: Option<i32>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(rename = "value", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub value: Option<Option<String>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<i32>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    #[serde(rename = "units", skip_serializing_if = "Option::is_none")]
    pub units: Option<String>,
    /// Returns the choices available for a given item.
    #[serde(rename = "choices", skip_serializing_if = "Option::is_none")]
    pub choices: Option<Vec<serde_json::Value>>,
    #[serde(rename = "model_name", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub model_name: Option<Option<String>>,
    #[serde(rename = "api_url", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub api_url: Option<Option<String>>,
    #[serde(rename = "typ", skip_serializing_if = "Option::is_none")]
    pub typ: Option<String>,
    /// Indicates if changing this setting requires confirmation
    #[serde(rename = "confirm", skip_serializing_if = "Option::is_none")]
    pub confirm: Option<bool>,
    #[serde(rename = "confirm_text", skip_serializing_if = "Option::is_none")]
    pub confirm_text: Option<String>,
}

impl PatchedUserSettings {
    /// Serializer for the InvenTreeUserSetting model.
    pub fn new() -> PatchedUserSettings {
        PatchedUserSettings {
            pk: None,
            key: None,
            value: None,
            name: None,
            description: None,
            user: None,
            r#type: None,
            units: None,
            choices: None,
            model_name: None,
            api_url: None,
            typ: None,
            confirm: None,
            confirm_text: None,
        }
    }
}

