/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatchedBomItem : Serializer for BomItem object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedBomItem {
    /// Select the parent assembly
    #[serde(rename = "part", skip_serializing_if = "Option::is_none")]
    pub part: Option<i32>,
    /// Select the component part
    #[serde(rename = "sub_part", skip_serializing_if = "Option::is_none")]
    pub sub_part: Option<i32>,
    /// BOM item reference
    #[serde(rename = "reference", skip_serializing_if = "Option::is_none")]
    pub reference: Option<String>,
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<f64>,
    /// Stock items for variant parts can be used for this BOM item
    #[serde(rename = "allow_variants", skip_serializing_if = "Option::is_none")]
    pub allow_variants: Option<bool>,
    /// This BOM item is inherited by BOMs for variant parts
    #[serde(rename = "inherited", skip_serializing_if = "Option::is_none")]
    pub inherited: Option<bool>,
    /// This BOM item is optional
    #[serde(rename = "optional", skip_serializing_if = "Option::is_none")]
    pub optional: Option<bool>,
    /// This BOM item is consumable (it is not tracked in build orders)
    #[serde(rename = "consumable", skip_serializing_if = "Option::is_none")]
    pub consumable: Option<bool>,
    #[serde(rename = "setup_quantity", skip_serializing_if = "Option::is_none")]
    pub setup_quantity: Option<f64>,
    #[serde(rename = "attrition", skip_serializing_if = "Option::is_none")]
    pub attrition: Option<f64>,
    #[serde(
        rename = "rounding_multiple",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub rounding_multiple: Option<Option<f64>>,
    /// BOM item notes
    #[serde(rename = "note", skip_serializing_if = "Option::is_none")]
    pub note: Option<String>,
    #[serde(rename = "pk", skip_serializing_if = "Option::is_none")]
    pub pk: Option<i32>,
    #[serde(
        rename = "pricing_min",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pricing_min: Option<Option<String>>,
    #[serde(
        rename = "pricing_max",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pricing_max: Option<Option<String>>,
    #[serde(
        rename = "pricing_min_total",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pricing_min_total: Option<Option<String>>,
    #[serde(
        rename = "pricing_max_total",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pricing_max_total: Option<Option<String>>,
    #[serde(
        rename = "pricing_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pricing_updated: Option<Option<String>>,
    #[serde(
        rename = "substitutes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub substitutes: Option<Option<Vec<models::BomItemSubstitute>>>,
    /// This BOM item has been validated
    #[serde(rename = "validated", skip_serializing_if = "Option::is_none")]
    pub validated: Option<bool>,
    #[serde(
        rename = "available_stock",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub available_stock: Option<Option<f64>>,
    #[serde(
        rename = "available_substitute_stock",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub available_substitute_stock: Option<Option<f64>>,
    #[serde(
        rename = "available_variant_stock",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub available_variant_stock: Option<Option<f64>>,
    #[serde(
        rename = "external_stock",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub external_stock: Option<Option<f64>>,
    #[serde(
        rename = "on_order",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub on_order: Option<Option<f64>>,
    #[serde(
        rename = "building",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub building: Option<Option<f64>>,
    #[serde(
        rename = "can_build",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub can_build: Option<Option<f64>>,
    #[serde(
        rename = "part_detail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub part_detail: Option<Option<Box<models::PartBrief>>>,
    #[serde(
        rename = "sub_part_detail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sub_part_detail: Option<Option<Box<models::PartBrief>>>,
    #[serde(
        rename = "category_detail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub category_detail: Option<Option<Box<models::Category>>>,
}

impl PatchedBomItem {
    /// Serializer for BomItem object.
    pub fn new() -> PatchedBomItem {
        PatchedBomItem {
            part: None,
            sub_part: None,
            reference: None,
            quantity: None,
            allow_variants: None,
            inherited: None,
            optional: None,
            consumable: None,
            setup_quantity: None,
            attrition: None,
            rounding_multiple: None,
            note: None,
            pk: None,
            pricing_min: None,
            pricing_max: None,
            pricing_min_total: None,
            pricing_max_total: None,
            pricing_updated: None,
            substitutes: None,
            validated: None,
            available_stock: None,
            available_substitute_stock: None,
            available_variant_stock: None,
            external_stock: None,
            on_order: None,
            building: None,
            can_build: None,
            part_detail: None,
            sub_part_detail: None,
            category_detail: None,
        }
    }
}
