/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatchedStockLocationType : Serializer for StockLocationType model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedStockLocationType {
    #[serde(rename = "pk", skip_serializing_if = "Option::is_none")]
    pub pk: Option<i32>,
    /// Name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Description (optional)
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Default icon for all locations that have no icon set (optional)
    #[serde(rename = "icon", skip_serializing_if = "Option::is_none")]
    pub icon: Option<String>,
    #[serde(
        rename = "location_count",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub location_count: Option<Option<i32>>,
}

impl PatchedStockLocationType {
    /// Serializer for StockLocationType model.
    pub fn new() -> PatchedStockLocationType {
        PatchedStockLocationType {
            pk: None,
            name: None,
            description: None,
            icon: None,
            location_count: None,
        }
    }
}
