/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatchedLabelTemplate : Serializer class for label template model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedLabelTemplate {
    #[serde(rename = "pk", skip_serializing_if = "Option::is_none")]
    pub pk: Option<i32>,
    /// Template name
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    /// Template description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "model_type", skip_serializing_if = "Option::is_none")]
    pub model_type: Option<models::TemplateModelTypeEnum>,
    #[serde(rename = "template", skip_serializing_if = "Option::is_none")]
    pub template: Option<String>,
    /// Template query filters (comma-separated list of key=value pairs)
    #[serde(rename = "filters", skip_serializing_if = "Option::is_none")]
    pub filters: Option<String>,
    /// Pattern for generating filenames
    #[serde(rename = "filename_pattern", skip_serializing_if = "Option::is_none")]
    pub filename_pattern: Option<String>,
    /// Template is enabled
    #[serde(rename = "enabled", skip_serializing_if = "Option::is_none")]
    pub enabled: Option<bool>,
    #[serde(rename = "revision", skip_serializing_if = "Option::is_none")]
    pub revision: Option<i32>,
    /// Save report output as an attachment against linked model instance when printing
    #[serde(rename = "attach_to_model", skip_serializing_if = "Option::is_none")]
    pub attach_to_model: Option<bool>,
    /// Label width, specified in mm
    #[serde(rename = "width", skip_serializing_if = "Option::is_none")]
    pub width: Option<f64>,
    /// Label height, specified in mm
    #[serde(rename = "height", skip_serializing_if = "Option::is_none")]
    pub height: Option<f64>,
}

impl PatchedLabelTemplate {
    /// Serializer class for label template model.
    pub fn new() -> PatchedLabelTemplate {
        PatchedLabelTemplate {
            pk: None,
            name: None,
            description: None,
            model_type: None,
            template: None,
            filters: None,
            filename_pattern: None,
            enabled: None,
            revision: None,
            attach_to_model: None,
            width: None,
            height: None,
        }
    }
}

