/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatchedMachineSetting : Serializer for the MachineSetting model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedMachineSetting {
    #[serde(rename = "pk", skip_serializing_if = "Option::is_none")]
    pub pk: Option<i32>,
    #[serde(rename = "key", skip_serializing_if = "Option::is_none")]
    pub key: Option<String>,
    #[serde(
        rename = "value",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub value: Option<Option<String>>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "type", skip_serializing_if = "Option::is_none")]
    pub r#type: Option<String>,
    /// Returns the choices available for a given item.
    #[serde(rename = "choices", skip_serializing_if = "Option::is_none")]
    pub choices: Option<Vec<serde_json::Value>>,
    #[serde(
        rename = "model_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub model_name: Option<Option<String>>,
    #[serde(rename = "model_filters", skip_serializing_if = "Option::is_none")]
    pub model_filters: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(
        rename = "api_url",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub api_url: Option<Option<String>>,
    #[serde(rename = "typ", skip_serializing_if = "Option::is_none")]
    pub typ: Option<String>,
    #[serde(rename = "units", skip_serializing_if = "Option::is_none")]
    pub units: Option<String>,
    #[serde(rename = "required", skip_serializing_if = "Option::is_none")]
    pub required: Option<bool>,
    /// Indicates if changing this setting requires confirmation
    #[serde(rename = "confirm", skip_serializing_if = "Option::is_none")]
    pub confirm: Option<bool>,
    #[serde(rename = "confirm_text", skip_serializing_if = "Option::is_none")]
    pub confirm_text: Option<String>,
    #[serde(rename = "config_type", skip_serializing_if = "Option::is_none")]
    pub config_type: Option<models::ConfigTypeEnum>,
}

impl PatchedMachineSetting {
    /// Serializer for the MachineSetting model.
    pub fn new() -> PatchedMachineSetting {
        PatchedMachineSetting {
            pk: None,
            key: None,
            value: None,
            name: None,
            description: None,
            r#type: None,
            choices: None,
            model_name: None,
            model_filters: None,
            api_url: None,
            typ: None,
            units: None,
            required: None,
            confirm: None,
            confirm_text: None,
            config_type: None,
        }
    }
}
