/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatchedNotificationMessage : Serializer for the InvenTreeUserSetting model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedNotificationMessage {
    #[serde(rename = "pk", skip_serializing_if = "Option::is_none")]
    pub pk: Option<i32>,
    /// Function to resolve generic object reference to target.
    #[serde(rename = "target", skip_serializing_if = "Option::is_none")]
    pub target: Option<std::collections::HashMap<String, serde_json::Value>>,
    /// Function to resolve generic object reference to source.
    #[serde(rename = "source", skip_serializing_if = "Option::is_none")]
    pub source: Option<std::collections::HashMap<String, serde_json::Value>>,
    #[serde(rename = "user", skip_serializing_if = "Option::is_none")]
    pub user: Option<i32>,
    #[serde(rename = "category", skip_serializing_if = "Option::is_none")]
    pub category: Option<String>,
    #[serde(rename = "name", skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(
        rename = "message",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub message: Option<Option<String>>,
    #[serde(rename = "creation", skip_serializing_if = "Option::is_none")]
    pub creation: Option<String>,
    /// Age of the message in seconds.
    #[serde(rename = "age", skip_serializing_if = "Option::is_none")]
    pub age: Option<i32>,
    /// Humanized age.
    #[serde(rename = "age_human", skip_serializing_if = "Option::is_none")]
    pub age_human: Option<String>,
    #[serde(rename = "read", skip_serializing_if = "Option::is_none")]
    pub read: Option<bool>,
}

impl PatchedNotificationMessage {
    /// Serializer for the InvenTreeUserSetting model.
    pub fn new() -> PatchedNotificationMessage {
        PatchedNotificationMessage {
            pk: None,
            target: None,
            source: None,
            user: None,
            category: None,
            name: None,
            message: None,
            creation: None,
            age: None,
            age_human: None,
            read: None,
        }
    }
}
