/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatchedReportAsset : Serializer class for the ReportAsset model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedReportAsset {
    #[serde(rename = "pk", skip_serializing_if = "Option::is_none")]
    pub pk: Option<i32>,
    #[serde(rename = "asset", skip_serializing_if = "Option::is_none")]
    pub asset: Option<String>,
    /// Asset file description
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

impl PatchedReportAsset {
    /// Serializer class for the ReportAsset model.
    pub fn new() -> PatchedReportAsset {
        PatchedReportAsset {
            pk: None,
            asset: None,
            description: None,
        }
    }
}

