/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatchedPluginActivate : Serializer for activating or deactivating a plugin.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedPluginActivate {
    /// Activate this plugin
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
}

impl PatchedPluginActivate {
    /// Serializer for activating or deactivating a plugin.
    pub fn new() -> PatchedPluginActivate {
        PatchedPluginActivate { active: None }
    }
}
