/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PatchedPurchaseOrderLineItem : Serializer class for the PurchaseOrderLineItem model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PatchedPurchaseOrderLineItem {
    #[serde(rename = "pk", skip_serializing_if = "Option::is_none")]
    pub pk: Option<i32>,
    /// Link to external page
    #[serde(rename = "link", skip_serializing_if = "Option::is_none")]
    pub link: Option<String>,
    /// Line item notes
    #[serde(rename = "notes", skip_serializing_if = "Option::is_none")]
    pub notes: Option<String>,
    /// Purchase Order
    #[serde(rename = "order", skip_serializing_if = "Option::is_none")]
    pub order: Option<i32>,
    /// Select project code for this order
    #[serde(
        rename = "project_code",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub project_code: Option<Option<i32>>,
    #[serde(rename = "quantity", skip_serializing_if = "Option::is_none")]
    pub quantity: Option<f64>,
    /// Line item reference
    #[serde(rename = "reference", skip_serializing_if = "Option::is_none")]
    pub reference: Option<String>,
    #[serde(
        rename = "target_date",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub target_date: Option<Option<String>>,
    #[serde(
        rename = "order_detail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub order_detail: Option<Option<Box<models::PurchaseOrder>>>,
    #[serde(
        rename = "project_code_label",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub project_code_label: Option<Option<String>>,
    #[serde(
        rename = "project_code_detail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub project_code_detail: Option<Option<Box<models::ProjectCode>>>,
    #[serde(
        rename = "part",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub part: Option<Option<i32>>,
    /// External Build Order to be fulfilled by this line item
    #[serde(
        rename = "build_order",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub build_order: Option<Option<i32>>,
    #[serde(
        rename = "overdue",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub overdue: Option<Option<bool>>,
    #[serde(rename = "received", skip_serializing_if = "Option::is_none")]
    pub received: Option<f64>,
    #[serde(
        rename = "purchase_price",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub purchase_price: Option<Option<String>>,
    /// Purchase price currency
    #[serde(
        rename = "purchase_price_currency",
        skip_serializing_if = "Option::is_none"
    )]
    pub purchase_price_currency: Option<String>,
    /// Automatically calculate purchase price based on supplier part data
    #[serde(rename = "auto_pricing", skip_serializing_if = "Option::is_none")]
    pub auto_pricing: Option<bool>,
    /// Destination for received items
    #[serde(
        rename = "destination",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub destination: Option<Option<i32>>,
    #[serde(rename = "total_price", skip_serializing_if = "Option::is_none")]
    pub total_price: Option<f64>,
    /// Merge items with the same part, destination and target date into one line item
    #[serde(rename = "merge_items", skip_serializing_if = "Option::is_none")]
    pub merge_items: Option<bool>,
    #[serde(
        rename = "sku",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub sku: Option<Option<String>>,
    #[serde(
        rename = "mpn",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub mpn: Option<Option<String>>,
    #[serde(
        rename = "ipn",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub ipn: Option<Option<String>>,
    #[serde(rename = "internal_part", skip_serializing_if = "Option::is_none")]
    pub internal_part: Option<i32>,
    #[serde(rename = "internal_part_name", skip_serializing_if = "Option::is_none")]
    pub internal_part_name: Option<String>,
    #[serde(
        rename = "build_order_detail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub build_order_detail: Option<Option<Box<models::Build>>>,
    #[serde(
        rename = "destination_detail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub destination_detail: Option<Option<Box<models::LocationBrief>>>,
    #[serde(
        rename = "part_detail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub part_detail: Option<Option<Box<models::PartBrief>>>,
    #[serde(
        rename = "supplier_part_detail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub supplier_part_detail: Option<Option<Box<models::SupplierPart>>>,
}

impl PatchedPurchaseOrderLineItem {
    /// Serializer class for the PurchaseOrderLineItem model.
    pub fn new() -> PatchedPurchaseOrderLineItem {
        PatchedPurchaseOrderLineItem {
            pk: None,
            link: None,
            notes: None,
            order: None,
            project_code: None,
            quantity: None,
            reference: None,
            target_date: None,
            order_detail: None,
            project_code_label: None,
            project_code_detail: None,
            part: None,
            build_order: None,
            overdue: None,
            received: None,
            purchase_price: None,
            purchase_price_currency: None,
            auto_pricing: None,
            destination: None,
            total_price: None,
            merge_items: None,
            sku: None,
            mpn: None,
            ipn: None,
            internal_part: None,
            internal_part_name: None,
            build_order_detail: None,
            destination_detail: None,
            part_detail: None,
            supplier_part_detail: None,
        }
    }
}
