/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PluginRegistryError : Serializer for a plugin registry error.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PluginRegistryError {
    #[serde(rename = "stage")]
    pub stage: String,
    #[serde(rename = "name")]
    pub name: String,
    #[serde(rename = "message")]
    pub message: String,
}

impl PluginRegistryError {
    /// Serializer for a plugin registry error.
    pub fn new(stage: String, name: String, message: String) -> PluginRegistryError {
        PluginRegistryError {
            stage,
            name,
            message,
        }
    }
}
