/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// PluginConfig : Serializer for a PluginConfig.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct PluginConfig {
    #[serde(rename = "pk")]
    pub pk: i32,
    /// Key of plugin
    #[serde(rename = "key")]
    pub key: String,
    /// Name of the plugin
    #[serde(
        rename = "name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub name: Option<Option<String>>,
    /// Name of the installed package, if the plugin was installed via PIP
    #[serde(
        rename = "package_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub package_name: Option<Option<String>>,
    /// Is the plugin active
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(rename = "meta")]
    pub meta: std::collections::HashMap<String, serde_json::Value>,
    #[serde(rename = "mixins")]
    pub mixins: std::collections::HashMap<String, serde_json::Value>,
    /// Return True if this is a 'builtin' plugin.
    #[serde(rename = "is_builtin")]
    pub is_builtin: bool,
    /// Is this plugin a sample app?
    #[serde(rename = "is_sample")]
    pub is_sample: bool,
    /// Simple check to determine if this plugin is installed.  A plugin might not be installed if it has been removed from the system, but the PluginConfig associated with it still exists.
    #[serde(rename = "is_installed")]
    pub is_installed: bool,
    /// Return True if this is a 'package' plugin.
    #[serde(rename = "is_package")]
    pub is_package: bool,
    #[serde(rename = "is_mandatory")]
    pub is_mandatory: bool,
}

impl PluginConfig {
    /// Serializer for a PluginConfig.
    pub fn new(
        pk: i32,
        key: String,
        meta: std::collections::HashMap<String, serde_json::Value>,
        mixins: std::collections::HashMap<String, serde_json::Value>,
        is_builtin: bool,
        is_sample: bool,
        is_installed: bool,
        is_package: bool,
        is_mandatory: bool,
    ) -> PluginConfig {
        PluginConfig {
            pk,
            key,
            name: None,
            package_name: None,
            active: None,
            meta,
            mixins,
            is_builtin,
            is_sample,
            is_installed,
            is_package,
            is_mandatory,
        }
    }
}
