/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReferenceStatusEnum : * `BuildStatus` - BuildStatus * `DataImportStatusCode` - DataImportStatusCode * `MachineStatus` - MachineStatus * `PurchaseOrderStatus` - PurchaseOrderStatus * `ReturnOrderLineStatus` - ReturnOrderLineStatus * `ReturnOrderStatus` - ReturnOrderStatus * `SalesOrderStatus` - SalesOrderStatus * `StockHistoryCode` - StockHistoryCode * `StockStatus` - StockStatus
/// * `BuildStatus` - BuildStatus * `DataImportStatusCode` - DataImportStatusCode * `MachineStatus` - MachineStatus * `PurchaseOrderStatus` - PurchaseOrderStatus * `ReturnOrderLineStatus` - ReturnOrderLineStatus * `ReturnOrderStatus` - ReturnOrderStatus * `SalesOrderStatus` - SalesOrderStatus * `StockHistoryCode` - StockHistoryCode * `StockStatus` - StockStatus
#[derive(Clone, Copy, Debug, Eq, PartialEq, Ord, PartialOrd, Hash, Serialize, Deserialize)]
pub enum ReferenceStatusEnum {
    #[serde(rename = "BuildStatus")]
    BuildStatus,
    #[serde(rename = "DataImportStatusCode")]
    DataImportStatusCode,
    #[serde(rename = "MachineStatus")]
    MachineStatus,
    #[serde(rename = "PurchaseOrderStatus")]
    PurchaseOrderStatus,
    #[serde(rename = "ReturnOrderLineStatus")]
    ReturnOrderLineStatus,
    #[serde(rename = "ReturnOrderStatus")]
    ReturnOrderStatus,
    #[serde(rename = "SalesOrderStatus")]
    SalesOrderStatus,
    #[serde(rename = "StockHistoryCode")]
    StockHistoryCode,
    #[serde(rename = "StockStatus")]
    StockStatus,
}

impl std::fmt::Display for ReferenceStatusEnum {
    fn fmt(&self, f: &mut std::fmt::Formatter) -> std::fmt::Result {
        match self {
            Self::BuildStatus => write!(f, "BuildStatus"),
            Self::DataImportStatusCode => write!(f, "DataImportStatusCode"),
            Self::MachineStatus => write!(f, "MachineStatus"),
            Self::PurchaseOrderStatus => write!(f, "PurchaseOrderStatus"),
            Self::ReturnOrderLineStatus => write!(f, "ReturnOrderLineStatus"),
            Self::ReturnOrderStatus => write!(f, "ReturnOrderStatus"),
            Self::SalesOrderStatus => write!(f, "SalesOrderStatus"),
            Self::StockHistoryCode => write!(f, "StockHistoryCode"),
            Self::StockStatus => write!(f, "StockStatus"),
        }
    }
}

impl Default for ReferenceStatusEnum {
    fn default() -> ReferenceStatusEnum {
        Self::BuildStatus
    }
}
