/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// ReportAsset : Serializer class for the ReportAsset model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct ReportAsset {
    #[serde(rename = "pk")]
    pub pk: i32,
    #[serde(rename = "asset")]
    pub asset: String,
    /// Asset file description
    #[serde(rename = "description")]
    pub description: String,
}

impl ReportAsset {
    /// Serializer class for the ReportAsset model.
    pub fn new(pk: i32, asset: String, description: String) -> ReportAsset {
        ReportAsset {
            pk,
            asset,
            description,
        }
    }
}
