/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// Role : Serializer for a roles associated with a given user.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct Role {
    #[serde(rename = "user")]
    pub user: i32,
    /// Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.
    #[serde(rename = "username")]
    pub username: String,
    /// Roles associated with the user.
    #[serde(rename = "roles")]
    pub roles: std::collections::HashMap<String, serde_json::Value>,
    /// Permissions associated with the user.
    #[serde(
        rename = "permissions",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub permissions: Option<Option<std::collections::HashMap<String, serde_json::Value>>>,
    /// Designates whether the user can log into this admin site.
    #[serde(rename = "is_staff", skip_serializing_if = "Option::is_none")]
    pub is_staff: Option<bool>,
    /// Designates that this user has all permissions without explicitly assigning them.
    #[serde(rename = "is_superuser", skip_serializing_if = "Option::is_none")]
    pub is_superuser: Option<bool>,
}

impl Role {
    /// Serializer for a roles associated with a given user.
    pub fn new(
        user: i32,
        username: String,
        roles: std::collections::HashMap<String, serde_json::Value>,
    ) -> Role {
        Role {
            user,
            username,
            roles,
            permissions: None,
            is_staff: None,
            is_superuser: None,
        }
    }
}
