/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// RuleSet : Serializer for a RuleSet.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct RuleSet {
    #[serde(rename = "pk")]
    pub pk: i32,
    /// Permission set  * `admin` - Admin * `part_category` - Part Categories * `part` - Parts * `stock_location` - Stock Locations * `stock` - Stock Items * `build` - Build Orders * `purchase_order` - Purchase Orders * `sales_order` - Sales Orders * `return_order` - Return Orders
    #[serde(rename = "name")]
    pub name: models::NameEnum,
    /// Return the translated label for this ruleset.
    #[serde(rename = "label")]
    pub label: String,
    /// Group
    #[serde(rename = "group")]
    pub group: i32,
    /// Permission to view items
    #[serde(rename = "can_view", skip_serializing_if = "Option::is_none")]
    pub can_view: Option<bool>,
    /// Permission to add items
    #[serde(rename = "can_add", skip_serializing_if = "Option::is_none")]
    pub can_add: Option<bool>,
    /// Permissions to edit items
    #[serde(rename = "can_change", skip_serializing_if = "Option::is_none")]
    pub can_change: Option<bool>,
    /// Permission to delete items
    #[serde(rename = "can_delete", skip_serializing_if = "Option::is_none")]
    pub can_delete: Option<bool>,
}

impl RuleSet {
    /// Serializer for a RuleSet.
    pub fn new(pk: i32, name: models::NameEnum, label: String, group: i32) -> RuleSet {
        RuleSet {
            pk,
            name,
            label,
            group,
            can_view: None,
            can_add: None,
            can_change: None,
            can_delete: None,
        }
    }
}
