/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SalesOrderShipmentAllocationItem : A serializer for allocating a single stock-item against a SalesOrder shipment.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SalesOrderShipmentAllocationItem {
    #[serde(rename = "line_item")]
    pub line_item: i32,
    #[serde(rename = "stock_item")]
    pub stock_item: i32,
    #[serde(rename = "quantity")]
    pub quantity: String,
}

impl SalesOrderShipmentAllocationItem {
    /// A serializer for allocating a single stock-item against a SalesOrder shipment.
    pub fn new(line_item: i32, stock_item: i32, quantity: String) -> SalesOrderShipmentAllocationItem {
        SalesOrderShipmentAllocationItem {
            line_item,
            stock_item,
            quantity,
        }
    }
}

