/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SelectionList : Serializer for a selection list.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelectionList {
    #[serde(rename = "pk")]
    pub pk: i32,
    /// Name of the selection list
    #[serde(rename = "name")]
    pub name: String,
    /// Description of the selection list
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Can this selection list be used?
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// Is this selection list locked?
    #[serde(rename = "locked", skip_serializing_if = "Option::is_none")]
    pub locked: Option<bool>,
    /// Plugin which provides the selection list
    #[serde(
        rename = "source_plugin",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub source_plugin: Option<Option<i32>>,
    /// Optional string identifying the source used for this list
    #[serde(rename = "source_string", skip_serializing_if = "Option::is_none")]
    pub source_string: Option<String>,
    #[serde(rename = "default")]
    pub default: Box<models::SelectionEntry>,
    /// Date and time that the selection list was created
    #[serde(rename = "created")]
    pub created: String,
    /// Date and time that the selection list was last updated
    #[serde(rename = "last_updated")]
    pub last_updated: String,
    #[serde(rename = "choices", skip_serializing_if = "Option::is_none")]
    pub choices: Option<Vec<models::SelectionEntry>>,
    #[serde(rename = "entry_count")]
    pub entry_count: i32,
}

impl SelectionList {
    /// Serializer for a selection list.
    pub fn new(
        pk: i32,
        name: String,
        default: models::SelectionEntry,
        created: String,
        last_updated: String,
        entry_count: i32,
    ) -> SelectionList {
        SelectionList {
            pk,
            name,
            description: None,
            active: None,
            locked: None,
            source_plugin: None,
            source_string: None,
            default: Box::new(default),
            created,
            last_updated,
            choices: None,
            entry_count,
        }
    }
}
