/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SelectionEntry : Serializer for a selection entry.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SelectionEntry {
    #[serde(rename = "id")]
    pub id: i32,
    /// Value of the selection list entry
    #[serde(rename = "value")]
    pub value: String,
    /// Label for the selection list entry
    #[serde(rename = "label")]
    pub label: String,
    /// Description of the selection list entry
    #[serde(rename = "description", skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    /// Is this selection list entry active?
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    /// Selection list to which this entry belongs
    #[serde(
        rename = "list",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub list: Option<Option<i32>>,
}

impl SelectionEntry {
    /// Serializer for a selection entry.
    pub fn new(id: i32, value: String, label: String) -> SelectionEntry {
        SelectionEntry {
            id,
            value,
            label,
            description: None,
            active: None,
            list: None,
        }
    }
}
