/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StockMergeItem : Serializer for a single StockItem within the StockMergeSerializer class.  Here, the individual StockItem is being checked for merge compatibility.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StockMergeItem {
    #[serde(rename = "item")]
    pub item: i32,
}

impl StockMergeItem {
    /// Serializer for a single StockItem within the StockMergeSerializer class.  Here, the individual StockItem is being checked for merge compatibility.
    pub fn new(item: i32) -> StockMergeItem {
        StockMergeItem {
            item,
        }
    }
}

