/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StockItemSerialNumbers : Serializer for extra serial number information about a stock item.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StockItemSerialNumbers {
    #[serde(rename = "next")]
    pub next: Box<models::StockItem>,
    #[serde(rename = "previous")]
    pub previous: Box<models::StockItem>,
}

impl StockItemSerialNumbers {
    /// Serializer for extra serial number information about a stock item.
    pub fn new(next: models::StockItem, previous: models::StockItem) -> StockItemSerialNumbers {
        StockItemSerialNumbers {
            next: Box::new(next),
            previous: Box::new(previous),
        }
    }
}
