/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// StockTracking : Serializer for StockItemTracking model.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct StockTracking {
    #[serde(rename = "pk")]
    pub pk: i32,
    #[serde(
        rename = "item",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub item: Option<Option<i32>>,
    #[serde(
        rename = "item_detail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub item_detail: Option<Option<Box<models::StockItem>>>,
    #[serde(
        rename = "part",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub part: Option<Option<i32>>,
    #[serde(
        rename = "part_detail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub part_detail: Option<Option<Box<models::PartBrief>>>,
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "deltas", deserialize_with = "Option::deserialize")]
    pub deltas: Option<serde_json::Value>,
    #[serde(rename = "label")]
    pub label: String,
    /// Entry notes
    #[serde(
        rename = "notes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub notes: Option<Option<String>>,
    #[serde(rename = "tracking_type")]
    pub tracking_type: i32,
    #[serde(
        rename = "user",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user: Option<Option<i32>>,
    #[serde(
        rename = "user_detail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub user_detail: Option<Option<Box<models::User>>>,
}

impl StockTracking {
    /// Serializer for StockItemTracking model.
    pub fn new(
        pk: i32,
        date: String,
        deltas: Option<serde_json::Value>,
        label: String,
        tracking_type: i32,
    ) -> StockTracking {
        StockTracking {
            pk,
            item: None,
            item_detail: None,
            part: None,
            part_detail: None,
            date,
            deltas,
            label,
            notes: None,
            tracking_type,
            user: None,
            user_detail: None,
        }
    }
}
