/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SupplierPriceBreak : Serializer for SupplierPriceBreak object.  Note that this inherits from the SupplierPriceBreakBriefSerializer, and does so to prevent circular serializer import issues.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SupplierPriceBreak {
    #[serde(rename = "pk")]
    pub pk: i32,
    #[serde(rename = "part")]
    pub part: i32,
    #[serde(rename = "quantity")]
    pub quantity: f64,
    #[serde(rename = "price", deserialize_with = "Option::deserialize")]
    pub price: Option<String>,
    /// Select currency from available options
    #[serde(rename = "price_currency", skip_serializing_if = "Option::is_none")]
    pub price_currency: Option<String>,
    #[serde(rename = "supplier")]
    pub supplier: i32,
    /// Timestamp of last update
    #[serde(rename = "updated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub updated: Option<Option<String>>,
}

impl SupplierPriceBreak {
    /// Serializer for SupplierPriceBreak object.  Note that this inherits from the SupplierPriceBreakBriefSerializer, and does so to prevent circular serializer import issues.
    pub fn new(pk: i32, part: i32, quantity: f64, price: Option<String>, supplier: i32) -> SupplierPriceBreak {
        SupplierPriceBreak {
            pk,
            part,
            quantity,
            price,
            price_currency: None,
            supplier,
            updated: None,
        }
    }
}

