/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SupplierPart : Serializer for SupplierPart object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SupplierPart {
    #[serde(rename = "available", skip_serializing_if = "Option::is_none")]
    pub available: Option<f64>,
    /// Date of last update of availability data
    #[serde(
        rename = "availability_updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub availability_updated: Option<Option<String>>,
    /// Supplier part description
    #[serde(
        rename = "description",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub description: Option<Option<String>>,
    #[serde(
        rename = "in_stock",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub in_stock: Option<Option<f64>>,
    #[serde(
        rename = "on_order",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub on_order: Option<Option<f64>>,
    /// URL for external supplier part link
    #[serde(
        rename = "link",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub link: Option<Option<String>>,
    /// Is this supplier part active?
    #[serde(rename = "active", skip_serializing_if = "Option::is_none")]
    pub active: Option<bool>,
    #[serde(
        rename = "manufacturer_detail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub manufacturer_detail: Option<Option<Box<models::CompanyBrief>>>,
    /// Select manufacturer part
    #[serde(
        rename = "manufacturer_part",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub manufacturer_part: Option<Option<i32>>,
    #[serde(
        rename = "manufacturer_part_detail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub manufacturer_part_detail: Option<Option<Box<models::ManufacturerPart>>>,
    #[serde(
        rename = "MPN",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub mpn: Option<Option<String>>,
    /// Notes
    #[serde(
        rename = "note",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub note: Option<Option<String>>,
    #[serde(rename = "pk")]
    pub pk: i32,
    /// Unique hash of barcode data
    #[serde(rename = "barcode_hash")]
    pub barcode_hash: String,
    /// Part packaging
    #[serde(
        rename = "packaging",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub packaging: Option<Option<String>>,
    /// Total quantity supplied in a single pack. Leave empty for single items.
    #[serde(rename = "pack_quantity", skip_serializing_if = "Option::is_none")]
    pub pack_quantity: Option<String>,
    #[serde(rename = "pack_quantity_native")]
    pub pack_quantity_native: f64,
    /// Select part
    #[serde(rename = "part")]
    pub part: i32,
    #[serde(
        rename = "pretty_name",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub pretty_name: Option<Option<String>>,
    /// Supplier stock keeping unit
    #[serde(rename = "SKU")]
    pub sku: String,
    #[serde(rename = "supplier")]
    pub supplier: i32,
    #[serde(
        rename = "supplier_detail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub supplier_detail: Option<Option<Box<models::CompanyBrief>>>,
    #[serde(
        rename = "updated",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub updated: Option<Option<String>>,
    /// Markdown notes (optional)
    #[serde(
        rename = "notes",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub notes: Option<Option<String>>,
    #[serde(
        rename = "part_detail",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub part_detail: Option<Option<Box<models::PartBrief>>>,
    #[serde(rename = "tags", skip_serializing_if = "Option::is_none")]
    pub tags: Option<Vec<String>>,
    #[serde(
        rename = "price_breaks",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub price_breaks: Option<Option<Vec<models::SupplierPriceBreakBrief>>>,
    #[serde(
        rename = "parameters",
        default,
        with = "::serde_with::rust::double_option",
        skip_serializing_if = "Option::is_none"
    )]
    pub parameters: Option<Option<Vec<models::Parameter>>>,
}

impl SupplierPart {
    /// Serializer for SupplierPart object.
    pub fn new(
        pk: i32,
        barcode_hash: String,
        pack_quantity_native: f64,
        part: i32,
        sku: String,
        supplier: i32,
    ) -> SupplierPart {
        SupplierPart {
            available: None,
            availability_updated: None,
            description: None,
            in_stock: None,
            on_order: None,
            link: None,
            active: None,
            manufacturer_detail: None,
            manufacturer_part: None,
            manufacturer_part_detail: None,
            mpn: None,
            note: None,
            pk,
            barcode_hash,
            packaging: None,
            pack_quantity: None,
            pack_quantity_native,
            part,
            pretty_name: None,
            sku,
            supplier,
            supplier_detail: None,
            updated: None,
            notes: None,
            part_detail: None,
            tags: None,
            price_breaks: None,
            parameters: None,
        }
    }
}
