/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// SupplierPriceBreakBrief : Brief serializer for SupplierPriceBreak object.  Used to provide a list of price breaks against the SupplierPart object.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct SupplierPriceBreakBrief {
    #[serde(rename = "pk")]
    pub pk: i32,
    #[serde(rename = "part")]
    pub part: i32,
    #[serde(rename = "quantity")]
    pub quantity: f64,
    #[serde(rename = "price", deserialize_with = "Option::deserialize")]
    pub price: Option<String>,
    /// Select currency from available options  * `AUD` - AUD - Australian Dollar * `CAD` - CAD - Canadian Dollar * `CNY` - CNY - Chinese Yuan * `EUR` - EUR - Euro * `GBP` - GBP - British Pound * `JPY` - JPY - Japanese Yen * `NZD` - NZD - New Zealand Dollar * `USD` - USD - US Dollar  Other valid currencies may be found in the 'CURRENCY_CODES' global setting.
    #[serde(rename = "price_currency", skip_serializing_if = "Option::is_none")]
    pub price_currency: Option<String>,
    #[serde(rename = "supplier")]
    pub supplier: i32,
    /// Timestamp of last update
    #[serde(rename = "updated", default, with = "::serde_with::rust::double_option", skip_serializing_if = "Option::is_none")]
    pub updated: Option<Option<String>>,
}

impl SupplierPriceBreakBrief {
    /// Brief serializer for SupplierPriceBreak object.  Used to provide a list of price breaks against the SupplierPart object.
    pub fn new(pk: i32, part: i32, quantity: f64, price: Option<String>, supplier: i32) -> SupplierPriceBreakBrief {
        SupplierPriceBreakBrief {
            pk,
            part,
            quantity,
            price,
            price_currency: None,
            supplier,
            updated: None,
        }
    }
}

