/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 * 
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// User : Serializer for a User.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct User {
    #[serde(rename = "pk")]
    pub pk: i32,
    /// Username
    #[serde(rename = "username")]
    pub username: String,
    /// First name of the user
    #[serde(rename = "first_name")]
    pub first_name: String,
    /// Last name of the user
    #[serde(rename = "last_name")]
    pub last_name: String,
    /// Email address of the user
    #[serde(rename = "email")]
    pub email: String,
}

impl User {
    /// Serializer for a User.
    pub fn new(pk: i32, username: String, first_name: String, last_name: String, email: String) -> User {
        User {
            pk,
            username,
            first_name,
            last_name,
            email,
        }
    }
}

