/*
 * InvenTree API
 *
 * API for InvenTree - the intuitive open source inventory management system
 *
 * The version of the OpenAPI document: 453
 *
 * Generated by: https://openapi-generator.tech
 */

use crate::models;
use serde::{Deserialize, Serialize};

/// VersionInformation : Serializer for a single version.
#[derive(Clone, Default, Debug, PartialEq, Serialize, Deserialize)]
pub struct VersionInformation {
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "date")]
    pub date: String,
    #[serde(rename = "gh", deserialize_with = "Option::deserialize")]
    pub gh: Option<String>,
    #[serde(rename = "text")]
    pub text: Vec<String>,
    #[serde(rename = "latest")]
    pub latest: bool,
}

impl VersionInformation {
    /// Serializer for a single version.
    pub fn new(
        version: String,
        date: String,
        gh: Option<String>,
        text: Vec<String>,
        latest: bool,
    ) -> VersionInformation {
        VersionInformation {
            version,
            date,
            gh,
            text,
            latest,
        }
    }
}
